//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "SGMessagesSuggestionsServiceDelegate.h"

@interface IMDSuggestions : NSObject
{
    id _sgService;
}

@property(retain) id sgService; // @synthesize sgService=_sgService;
- (id)suggestionsService:(id)arg1 needsContextForConversationIdentifier:(id)arg2 numberOfMessagesNeeded:(unsigned long long)arg3;
- (void)suggestionsFromMessage:(id)arg1 options:(unsigned long long)arg2 completionHandler:(id)arg3;
- (void)dealloc;
- (id)init;

@end

