//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface IMConnectionMonitor : NSObject
{
    NSString *_remoteHost;
    id _delegate;
}

+ (id)alloc;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
@property(readonly, retain, nonatomic) NSString *remoteHost; // @synthesize remoteHost=_remoteHost;
@property(readonly, nonatomic) BOOL isImmediatelyReachable;
@property(readonly, nonatomic) BOOL requiresDataConnectionActivation;
@property(nonatomic, setter=setDataConnectionActive:) BOOL isDataConnectionActive;
- (void)clear;
- (void)goDisconnected;
- (void)goConnectedWithLocalSocketAddress:(id)arg1 remoteSocketAddress:(id)arg2;
- (void)_setup;
- (void)dealloc;
- (id)initWithRemoteHost:(id)arg1 delegate:(id)arg2;

@end

