//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IMLocalObject, NSObject;

@interface IMMessageContext : NSObject
{
    NSObject *_xpcMessage;
    IMLocalObject *_localObject;
    id _context;
    BOOL _boost;
    NSObject *_voucher;
}

@property(retain) NSObject *voucher; // @synthesize voucher=_voucher;
@property(retain) id context; // @synthesize context=_context;
@property BOOL shouldBoost; // @synthesize shouldBoost=_boost;
@property(retain) IMLocalObject *localObject; // @synthesize localObject=_localObject;
@property(retain) NSObject *xpcMessage; // @synthesize xpcMessage=_xpcMessage;
- (void)dealloc;
- (id)init;

@end

