//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>

@interface IMPair<A, B> : NSObject
{
    A _first;
    B _second;
}

+ (id)pairWithFirst:(A)arg1 second:(B)arg2;
@property(retain) B second; // @synthesize second=_second;
@property(retain) A first; // @synthesize first=_first;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithFirst:(A)arg1 second:(B)arg2;

@end

