//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface IMPerfSinkPair : NSObject
{
    id _behavior;
    id _sink;
}

@property(readonly, nonatomic) id sink; // @synthesize sink=_sink;
@property(readonly, nonatomic) id behavior; // @synthesize behavior=_behavior;
- (void)dealloc;
- (id)initWithBehavior:(id)arg1 sink:(id)arg2;

@end

