//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject;

@interface IMPurgableObject : NSObject
{
    id _instanceObject;
    id _setupBlock;
    id _cleanupBlock;
    NSObject *_queue;
}

- (void)_receivedMemoryWarning:(id)arg1;
- (id)instance;
- (void)_cleanupInstance;
- (void)_setupInstance;
- (void)dealloc;
- (id)initWithSetupBlock:(id)arg1 cleanupBlock:(id)arg2 queue:(id)arg3;

@end

