//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject, NSRecursiveLock, NSString, Protocol;

@interface IMRemoteObjectInternal : NSObject
{
    NSRecursiveLock *_lock;
    NSObject *_connection;
    NSObject *_queue;
    long long _deathPostPredicate;
    Protocol *_protocol;
    NSString *_portName;
    NSString *_processName;
    BOOL _willBeTerminated;
    int _pid;
}

@end

