//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface IMBatteryStatus : NSObject
{
    id _testDelegate;
}


@property(nonatomic) __weak id testDelegate; // @synthesize testDelegate=_testDelegate;
@property(readonly, getter=isCharging) BOOL charging;

@end

