//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "IMSingletonOverriding.h"

@class NSString;

@interface IMSingletonOverride : NSObject
{
    id _overriddenSingleton;
}


@property __weak id overriddenSingleton; // @synthesize overriddenSingleton=_overriddenSingleton;
- (BOOL)shouldInvokeSelector:(SEL)arg1 onSingleton:(id)arg2;
- (void)didOverrideSingleton:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

