name: barcelona

fileGroups:
  - project.yml
  - README.md
  - Makefile
  - BUILDING.md
  - Scripts
  - XCSpec

include:
  - XCSpec/spm.yaml
  - XCSpec/templates.yaml
  - XCSpec/barcelona.yaml
  - XCSpec/beeper.yaml

options:
  deploymentTarget:
    macOS: 10.15
    iOS: 13.0
  defaultConfig: Debug
  bundleIdPrefix: com.barcelona
  createIntermediateGroups: true

configFiles:
  Debug: XCSpec/Settings/Barcelona.xcconfig
  Release: XCSpec/Settings/Barcelona.xcconfig
