//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNAutocompleteSearchProvider.h"

@class NSString;

@interface _CNAutocompleteCachingSearchProvider : NSObject
{
    id _localSearchFuture;
    id _recentsSearchFuture;
    id _suggestionsSearchFuture;
    id _duetSearchFuture;
    id _localExtensionSearchesFuture;
    id _directoryServerSearchFuture;
    id _calendarServerSearchFuture;
}


- (id)calendarServerSearch;
- (id)directoryServerSearch;
- (id)localExtensionSearches;
- (id)duetSearch;
- (id)suggestionsSearch;
- (id)recentsSearch;
- (id)localSearch;
- (id)initWithSearchProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

