//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray;

@protocol CNAutocompleteSearchProvider <NSObject>
- (id)calendarServerSearch;
- (id)directoryServerSearch;
- (NSArray *)localExtensionSearches;
- (id)duetSearch;
- (id)suggestionsSearch;
- (id)recentsSearch;
- (id)localSearch;
@end

