//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class CNAutocompleteStoreQueryContext, CNAutocompleteUserSession;

@interface CNAutocompleteStoreQueryHelper : NSObject
{
    id _searchProvider;
    id _delegate;
    id _scheduler;
    CNAutocompleteStoreQueryContext *_queryContext;
    id _probeProvider;
    CNAutocompleteUserSession *_userSession;
}


@property(readonly, nonatomic) CNAutocompleteUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) id probeProvider; // @synthesize probeProvider=_probeProvider;
@property(readonly, nonatomic) CNAutocompleteStoreQueryContext *queryContext; // @synthesize queryContext=_queryContext;
@property(readonly, nonatomic) id scheduler; // @synthesize scheduler=_scheduler;
@property(readonly, nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id searchProvider; // @synthesize searchProvider=_searchProvider;
- (id)executeFetchRequest:(id)arg1 delegate:(id)arg2 delegateToken:(id)arg3;
- (id)initWithSearchProvider:(id)arg1 delegate:(id)arg2 probeProvider:(id)arg3 scheduler:(id)arg4 userSession:(id)arg5;

@end

