//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNAutocompleteSearch.h"

@class CRRecentContactsLibrary, NSString;

@interface CNAutocompleteRecentsSearch : NSObject
{
    CRRecentContactsLibrary *_library;
}


@property(retain, nonatomic) CRRecentContactsLibrary *library; // @synthesize library=_library;
- (id)autocompleteResultsForRecentContacts:(id)arg1 request:(id)arg2;
- (id)executeRequest:(id)arg1 completionHandler:(id)arg2;
- (id)initWithCoreRecentContactsLibrary:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

