//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNAutocompleteSearch.h"

@class CNContactStore, NSString;

@interface CNAutocompleteDuetSearch : NSObject
{
    id _peopleSuggesterFactory;
    CNContactStore *_contactStore;
}

+ (id)constrainMechanismsForSearchType:(unsigned long long)arg1;
+ (unsigned long long)predictedResultLimit;
+ (void)configureSettings:(id)arg1 withFetchRequest:(id)arg2;
+ (void)configureContext:(id)arg1 withFetchRequest:(id)arg2;

@property(readonly, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
@property(readonly, nonatomic) id peopleSuggesterFactory; // @synthesize peopleSuggesterFactory=_peopleSuggesterFactory;
- (id)resultValueForCDContact:(id)arg1;
- (long long)addressTypeForCDContact:(id)arg1;
- (id)autocompleteResultsFromSuggesterResults:(id)arg1 factory:(id)arg2;
- (id)suggesterSettingsForFetchRequest:(id)arg1;
- (id)suggesterContextForFetchRequest:(id)arg1;
- (id)querySuggester:(id)arg1 withContext:(id)arg2 settings:(id)arg3;
- (id)executeRequest:(id)arg1 completionHandler:(id)arg2;
- (id)peopleSuggester;
- (id)initWithPeopleSuggesterFactory:(id)arg1 contactStore:(id)arg2;
- (id)initWithPeopleSuggesterFactory:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

