//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNCancelable.h"

@class CNAutocompleteDelegateWrapper, CNAutocompleteFetchRequest, CNAutocompleteUserSession, CNCancelationToken, NSString;

@interface CNAutocompleteQuery : NSObject 
{
    CNAutocompleteFetchRequest *_request;
    CNAutocompleteDelegateWrapper *_delegate;
    id _scheduler;
    CNCancelationToken *_cancelationToken;
    id _searchProvider;
    id _probeProvider;
    CNAutocompleteUserSession *_userSession;
    id  _delegateToken;
    id _sourceInclusionPolicy;
}

+ (id)observableWithSupplementalResultsForQuery:(id)arg1;
+ (void)configureNetworkActivityHandlersForBuilder:(id)arg1 query:(id)arg2;
+ (void)configureNetworkPolicyForBuilder:(id)arg1 query:(id)arg2;
+ (void)configureNetworkForBuilder:(id)arg1 query:(id)arg2;
+ (BOOL)shouldPerformQueryForRequest:(id)arg1;
+ (id)observableForQuery:(id)arg1 context:(id)arg2;
+ (BOOL)shouldSortResultsForPolicy:(id)arg1;
+ (BOOL)searchTypeSupportsSuppressionOfAlreadyChosenAddresses:(unsigned long long)arg1;
+ (BOOL)shouldSuppressAddressesAlreadyChosenForRequest:(id)arg1;
+ (id)queryWithRequest:(id)arg1 searchProvider:(id)arg2 delegate:(id)arg3 probeProvider:(id)arg4 scheduler:(id)arg5 userSession:(id)arg6 delegateToken:(id)arg7;

@property(retain) id sourceInclusionPolicy; // @synthesize sourceInclusionPolicy=_sourceInclusionPolicy;
@property __weak id  delegateToken; // @synthesize delegateToken=_delegateToken;
@property(retain) CNAutocompleteUserSession *userSession; // @synthesize userSession=_userSession;
@property(retain) id probeProvider; // @synthesize probeProvider=_probeProvider;
@property(retain) id searchProvider; // @synthesize searchProvider=_searchProvider;
@property(retain) CNCancelationToken *cancelationToken; // @synthesize cancelationToken=_cancelationToken;
@property(retain) id scheduler; // @synthesize scheduler=_scheduler;
@property(retain) CNAutocompleteDelegateWrapper *delegate; // @synthesize delegate=_delegate;
@property(copy) CNAutocompleteFetchRequest *request; // @synthesize request=_request;
- (void)cancel;
- (void)searchOperationsHaveFinished;
- (void)searchOperationsHaveEndedNetworkActivity;
- (void)searchOperationsHaveBegunNetworkActivity;
- (void)searchOperationEncounteredError:(id)arg1;
- (void)searchOperationReportedResults:(id)arg1;
- (id)executeWithContext:(id)arg1;
- (id)execute;
- (id)makeDelegateWrapperWithDelegate:(id)arg1 forRequest:(id)arg2 sourceInclusionPolicy:(id)arg3 userSession:(id)arg4;
- (id)initWithRequest:(id)arg1 searchProvider:(id)arg2 delegate:(id)arg3 probeProvider:(id)arg4 scheduler:(id)arg5 userSession:(id)arg6 delegateToken:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

