//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNAutocompleteSearch.h"

@class CNContactStore, NSString;

@interface CNAutocompleteLocalSearch : NSObject
{
    CNContactStore *_contactStore;
    CNContactStore *_contactFetcherStore;
}


@property(retain, nonatomic) CNContactStore *contactFetcherStore; // @synthesize contactFetcherStore=_contactFetcherStore;
@property(retain, nonatomic) CNContactStore *contactStore; // @synthesize contactStore=_contactStore;
- (id)groupsForRequest:(id)arg1 contactStore:(id)arg2 contactFetcherStore:(id)arg3;
- (id)peopleForRequest:(id)arg1 contactStore:(id)arg2 contactFetcherStore:(id)arg3;
- (id)executeRequest:(id)arg1 completionHandler:(id)arg2;
- (id)initWithContactStore:(id)arg1 contactFetcherStore:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

