//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class CNAutocompleteFetchRequest, CNAutocompleteUsageMonitor, NSDate, NSObject, _CNAutocompleteUserSessionDisplayedResults;

@interface CNAutocompleteUserSession : NSObject
{
    id _probeProvider;
    CNAutocompleteFetchRequest *_currentRequest;
    unsigned long long _currentBatch;
    _CNAutocompleteUserSessionDisplayedResults *_lastDisplayedResults;
    NSDate *_requestStartTime;
    CNAutocompleteUsageMonitor *_usageMonitor;
    NSObject *_syncQueue;
    id _duetResultsFuture;
}


@property(retain, nonatomic) id duetResultsFuture; // @synthesize duetResultsFuture=_duetResultsFuture;
@property(retain, nonatomic) NSObject *syncQueue; // @synthesize syncQueue=_syncQueue;
@property(retain, nonatomic) CNAutocompleteUsageMonitor *usageMonitor; // @synthesize usageMonitor=_usageMonitor;
@property(retain, nonatomic) NSDate *requestStartTime; // @synthesize requestStartTime=_requestStartTime;
@property(retain, nonatomic) _CNAutocompleteUserSessionDisplayedResults *lastDisplayedResults; // @synthesize lastDisplayedResults=_lastDisplayedResults;
@property(nonatomic) unsigned long long currentBatch; // @synthesize currentBatch=_currentBatch;
@property(retain, nonatomic) CNAutocompleteFetchRequest *currentRequest; // @synthesize currentRequest=_currentRequest;
@property(readonly, nonatomic) id probeProvider; // @synthesize probeProvider=_probeProvider;
- (void)_resetState;
- (void)didSelectResult:(id)arg1 atSortedIndex:(unsigned long long)arg2;
- (void)didReceiveResults:(id)arg1 forRequest:(id)arg2;
- (void)willStartExecutingRequest:(id)arg1;
- (void)willStartDuetRequestWithMatchingResultsFuture:(id)arg1;
- (id)initWithProbeProvider:(id)arg1;

@end

