//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNAutocompleteFetchDelegate.h"

@class NSString;

@interface CNAutocompleteFetchBlockDelegate : NSObject
{
    id _resultHandler;
    id _errorHandler;
    id _finishHandler;
    id _beganNetworkActivityHandler;
    id _endedNetworkActivityHandler;
    id _supplementalResultHandler;
    id _adjustmentHandler;
    id _willSortHandler;
    id _comparatorHandler;
}


@property(copy) id comparatorHandler; // @synthesize comparatorHandler=_comparatorHandler;
@property(copy) id willSortHandler; // @synthesize willSortHandler=_willSortHandler;
@property(copy) id adjustmentHandler; // @synthesize adjustmentHandler=_adjustmentHandler;
@property(copy) id supplementalResultHandler; // @synthesize supplementalResultHandler=_supplementalResultHandler;
@property(copy) id endedNetworkActivityHandler; // @synthesize endedNetworkActivityHandler=_endedNetworkActivityHandler;
@property(copy) id beganNetworkActivityHandler; // @synthesize beganNetworkActivityHandler=_beganNetworkActivityHandler;
@property(copy) id finishHandler; // @synthesize finishHandler=_finishHandler;
@property(copy) id errorHandler; // @synthesize errorHandler=_errorHandler;
@property(copy) id resultHandler; // @synthesize resultHandler=_resultHandler;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)resultComparatorForAutocompleteFetch:(id)arg1;
- (void)autocompleteFetch:(id)arg1 willSortResults:(id)arg2;
- (id)autocompleteFetch:(id)arg1 willAdjustResults:(id)arg2;
- (BOOL)autocompleteFetch:(id)arg1 shouldExpectSupplementalResultsForRequest:(id)arg2 completionHandler:(id)arg3;
- (void)autocompleteFetchDidEndNetworkActivity:(id)arg1;
- (void)autocompleteFetchDidBeginNetworkActivity:(id)arg1;
- (void)autocompleteFetch:(id)arg1 didFailWithError:(id)arg2;
- (void)autocompleteFetchDidFinish:(id)arg1;
- (void)autocompleteFetch:(id)arg1 didReceiveResults:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

