//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class CNAutocompleteFetchRequest, NSArray, NSDictionary, NSError;

@protocol CNAutocompleteFetchDelegate <NSObject>
- (void)autocompleteFetch:(id )arg1 didFailWithError:(NSError *)arg2;
- (void)autocompleteFetch:(id )arg1 didReceiveResults:(NSArray *)arg2;

@optional
- (long long (^)(id, id))resultComparatorForAutocompleteFetch:(id )arg1;
- (void)autocompleteFetch:(id )arg1 willSortResults:(NSArray *)arg2;
- (NSDictionary *)autocompleteFetch:(id )arg1 willAdjustResults:(NSArray *)arg2;
- (BOOL)autocompleteFetch:(id )arg1 shouldExpectSupplementalResultsForRequest:(CNAutocompleteFetchRequest *)arg2 completionHandler:(void (^)(NSArray *, NSError *))arg3;
- (void)autocompleteFetchDidEndNetworkActivity:(id )arg1;
- (void)autocompleteFetchDidBeginNetworkActivity:(id )arg1;
- (void)autocompleteFetchDidFinish:(id )arg1;
@end

