//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ContactsFoundation/CNObservable.h>

@interface CNObservable (CNAutocomplete)
- (id)networkObservableWithActivityDidStartHandler:(id)arg1 activityDidStopHandler:(id)arg2 timeoutDelay:(double)arg3 subscriptionDelay:(double)arg4 scheduler:(id)arg5;
- (id)localObservableWithScheduler:(id)arg1 doOnTimeout:(id)arg2;
- (id)localObservableWithScheduler:(id)arg1;
- (id)activityIndicatingObservableWithActivityDidStartHandler:(id)arg1 activityDidStopHandler:(id)arg2;
- (id)autocompleteTimeoutAfterDelay:(double)arg1 doOnTimeout:(id)arg2 scheduler:(id)arg3;
@end

