//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>
#import "IMMessage.h"

@class NSMutableDictionary;

@interface IMChatHistoryController : NSObject
{
    NSMutableDictionary *_runningQueries;
}

+ (IMChatHistoryController*)sharedInstance;
@property(retain) NSMutableDictionary *_runningQueries; // @synthesize _runningQueries;
- (void)messageQuery:(id)arg1 finishedWithResult:(id)arg2 chatGUIDs:(id)arg3;
- (void)loadMessageWithGUID:(NSString*)arg1 completionBlock:(void (^)(IMMessage *message))arg2;
- (void)dealloc;
- (id)init;

@end

