//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMItem, NSString;

@interface IMChatItem : NSObject
{
    IMItem *_item;
}

@property(readonly, retain, nonatomic) NSString *balloonBundleID;
- (void)_setTimeAdded:(id)arg1;
- (NSDate*)_timeAdded;
- (id)_timeStale;
- (IMItem*)_item;
- (id)_initWithItem:(id)arg1;
@property(readonly, nonatomic) BOOL canDelete;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (BOOL)itemIsThreadOriginator API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));
- (BOOL)itemIsThreadOriginatorWithThreadIdentifier:(NSString*)arg1 API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));
- (NSString*)threadGroupIdentifier API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));

- (BOOL) itemIsReply API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));
- (BOOL) itemIsReplyContextPreview API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));
- (BOOL) itemIsReplyCount API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));
- (BOOL) canReply API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));

@end

