//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMFoundation/IMFoundation.h>

@class IMItem;
@class IMMessageItem;

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnullability-completeness"

typedef NS_ENUM(uint32_t, FZBlockingMode) {
    kFZBlockingAllowAll = 0,
    kFZBlockingAllowBuddies,
    kFZBlockingAllowListed,
    kFZBlockingBlockListed,
    kFZBlockingBlockAll,
};

typedef NS_ENUM(uint32_t, FZServiceStatus) {
    kFZServiceLoggedOut,
    kFZServiceDisconnected,
    kFZServiceLoggingOut,
    kFZServiceLoggingIn,
    kFZServiceLoggedIn
};

typedef NS_ENUM(int32_t, FZDisconnectReason) {
    kFZReasonNoReason = -1,
    kFZReasonUnknown = 0,
    kFZReasonBadUserOrPass,
    kFZReasonTempOffline,
    kFZReasonDisabled,
    kFZReasonLoggedInElsewhere,
    kFZReasonBadSSLCertificate,
    kFZReasonSSLFailed,
    kFZReasonRateLimited,
    kFZReasonNetworkError,
    kFZReasonNetworkDisconnectedError,
    kFZReasonNetworkConnectionError,
    kFZReasonBadOAuthToken,
};

typedef NS_ENUM(UInt8, IMChatStyle) {
    IMInstantMessageChatStyle = '-',
    IMGroupChatStyle          = '+',
    IMRoomChatStyle           = '#',
};

typedef NS_ENUM(int32_t, FZChatMemberStatus) {
    kFZChatMemberInviteFailed = -1,
    kFZChatMemberDeciding,
    kFZChatMemberDeclined,
    kFZChatMemberJoined,
    kFZChatMemberLeft,
    kFZChatMemberKicked,
    kFZChatMemberBanned
};

typedef NS_ENUM(int32_t, FZChatStatus) {
    kFZChatCouldntJoin = -1,
    kFZChatUnjoined,
    kFZChatJoining,
    kFZChatJoined,
    kFZChatLeft,
    kFZChatKicked,
    kFZChatBanned,
    kFZChatPasswordNeeded
};

@protocol IMDaemonListenerProtocol <NSObject>
@optional
- (void) setupComplete:(BOOL)success info:(NSDictionary *)info;
- (void) setupComplete;
- (void) pendingVCRequestComplete;
- (void) pendingACRequestComplete;
- (void) vcCapabilitiesChanged:(uint32_t)capabilities;
- (void) defaultsChanged: (NSDictionary*)defaults forService:(NSString *)name;
- (void) activeAccountsChanged: (NSArray*)accounts forService:(NSString *)name;
- (void) account:(NSString *)account defaults:(NSDictionary *)defaults blockList:(NSArray *)blockList allowList:(NSArray *)allowList blockingMode:(FZBlockingMode)blockingMode blockIdleStatus:(BOOL)blockIdle status:(NSDictionary *)status capabilities:(uint32_t)capabilities serviceLoginStatus:(FZServiceStatus)serviceLoginStatus loginStatusMessage:(NSString *)message;
- (void) account: (NSString *)account loginStatusChanged: (FZServiceStatus)status message: (NSString*)message reason: (FZDisconnectReason)reason properties: (NSDictionary*) props;
- (void) account: (NSString *)account defaultsChanged:(NSDictionary *)defaults;
- (void) account: (NSString *)account capabilitiesChanged: (uint32_t)capabilities;
- (void) accountAdded:(NSString *)account defaults:(NSDictionary *)defaults service:(NSString *)internalName;
- (void) accountRemoved:(NSString *)account;
- (void) account: (NSString *)account buddyPropertiesChanged: (NSArray*)info;
- (void) account:(NSString *)account blockListChanged:(NSArray *)blockList;
- (void) account:(NSString *)account allowListChanged:(NSArray *)allowList;
- (void) account:(NSString *)account blockingModeChanged:(FZBlockingMode)blockingMode;
- (void) account:(NSString *)account blockIdleStatusChanged:(BOOL)blockIdle;
- (void) account: (NSString *)account buddyPictureChanged: (NSString*)buddyID imageData:(NSData*)data imageHash:(NSString*)hash;
- (void) account: (NSString *)account groupsChanged: (NSArray*)groups  error: (NSError*)error;
- (void) account:(NSString *)account buddyProperties:(NSDictionary *) properties buddyPictures:(NSDictionary *)pictures;
- (void) account: (NSString *)account handleSubscriptionRequestFrom: (NSDictionary *) buddyInfo withMessage: (NSString *) message;
- (void) account:(NSString *)accountID buddyInfo:(NSDictionary *)buddyInfo commandReceived:(NSNumber *)command properties:(NSDictionary *)properties;
- (void) account:(NSString *)accountID buddyInfo:(NSDictionary *)buddyInfo commandDelivered:(NSNumber *)command properties:(NSDictionary *)properties;
- (void) chat:(NSString *)persistentIdentifier updated:(NSDictionary *)updateDictionary;
- (void) chat:(NSString *)persistentIdentifier propertiesUpdated:(NSDictionary *)properties;
- (void) chat:(NSString *)persistentIdentifier displayNameUpdated:(NSString *)displayName;
- (void) chat:(NSString *)guid lastAddressedHandleUpdated:(NSString *)lastAddressedHandle;
- (void) chat:(NSString *)guid lastAddressedSIMIDUpdated:(NSString *)lastAddressedSIMID;
- (void) chat:(NSString *)persistentIdentifier isFilteredUpdated:(BOOL)isFiltered;
- (void) chat:(NSString *)persistentIdentifier engramIDUpdated:(NSString *)engramID;
- (void) leftChat:(NSString *)persistentIdentifier;
- (void) engroupParticipantsUpdatedForChat:(NSString *)persistentIdentifier;
- (void) loadedChats:(NSArray<NSDictionary *> *)chats;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties invitationReceived:(IMMessageItem *)msg;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties updateProperties:(NSDictionary *)update;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties groupID:(NSString *)groupID chatPersonCentricID:(NSString *) personCentricID messageSent:(IMMessageItem *)msg;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties groupID:(NSString *)groupID chatPersonCentricID:(NSString *) personCentricID messageReceived:(IMItem *)msg;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties groupID:(NSString *)groupID chatPersonCentricID:(NSString *) personCentricID messagesReceived:(NSArray<IMItem *> *)messages messagesComingFromStorage:(BOOL)fromStorage;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties messageUpdated:(IMItem *)msg;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties notifySentMessage:(IMMessageItem *)msg sendTime:(NSNumber *)sendTime;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties messagesUpdated:(NSArray<NSObject*> *)messages;
- (void) service:(NSString *)serviceID chat:(NSString*)chatIdentifier style:(IMChatStyle)chatStyle messagesUpdated:(NSArray*)messages;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties error:(NSError *)error;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties groupID:(NSString *)groupID chatPersonCentricID:(NSString *) personCentricID statusChanged:(FZChatStatus)status handleInfo:(NSArray *)handleInfo;
- (void) account:(NSString *)accountUniqueID chat:(NSString *)chatIdentifier style:(IMChatStyle)chatStyle chatProperties:(NSDictionary *)properties member:(NSDictionary *)memberInfo statusChanged:(FZChatMemberStatus)status;
- (void) messageQuery:(NSString *)queryID finishedWithResult:(IMMessageItem *)message chatGUIDs:(NSArray *)chatGUIDs;
- (void) historyQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)services finishedWithResult:(NSArray *)messages limit:(NSUInteger)limit;
- (void) pagedHistoryQuery:(NSString *)queryID chatID:(NSString *)chatID services:(NSArray *)services numberOfMessagesBefore:(NSUInteger)numberOfMessagesBefore numberOfMessagesAfter:(NSUInteger)numberOfMessagesAfter finishedWithResult:(NSArray *)serializedItems;
- (void) attachmentQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)services finishedWithResult:(NSArray *)filenames;
- (void) uncachedAttachmentCountQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)services finishedWithResult:(NSNumber *)countOfAttachmentsNotCachedLocally;
- (void) isDownloadingQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)services finishedWithResult:(BOOL)isCurrentlyDownloadingPurgedAssets;
- (void) downloadedPurgedAssetBatchForChatIDs:(NSArray<NSString *> *)chatIdentifiers completedTransferGUIDs:(NSArray <NSString *> *)transferGUIDs;
- (void) finishedDownloadingPurgedAssetsForChatIDs:(NSArray<NSString *> *)chatIdentifiers;
- (void) markAsSpamQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)services finishedWithResult:(NSNumber *)countOfMessagesMarkedAsSpam;
- (void) historicalMessageGUIDsDeleted:(NSArray<NSString*> *)deletedGUIDs chatGUIDs:(NSArray<NSString*> *)chatGUIDs queryID:(NSString *)queryID;
- (void) frequentRepliesQuery:(NSString *)queryID chatID:(NSString *)chatIdentifier services:(NSArray *)queryServices finishedWithResult:(NSArray *)frequentReplies limit:(NSUInteger)limit;
- (void) chatLoadedWithChatIdentifier:(NSString *)chatIdentifier chats:(NSArray *)chatDictionaries;
- (void) standaloneFileTransferRegistered: (NSString *)guid;
- (void) fileTransfer: (NSString *)guid createdWithProperties: (NSDictionary *)properties;
- (void) fileTransfer: (NSString *)guid updatedWithProperties: (NSDictionary *)properties;
- (void) fileTransfers:(NSArray *)guids createdWithLocalPaths:(NSArray *)paths;
- (void) fileTransfer: (NSString *)guid updatedWithCurrentBytes: (uint64_t)currentBytes totalBytes: (uint64_t)totalBytes averageTransferRate: (uint64_t)averageTransferRate;
- (void) fileTransfer:(NSString *)guid highQualityDownloadSucceededWithPath:(NSString *)path;
- (void) fileTransferHighQualityDownloadFailed:(NSString *)guid;
- (void) account: (NSString *)account conference:(NSString *)conference receivedInvitationFrom: (NSDictionary*)buddyInfo  properties: (NSDictionary*)props;
- (void) account: (NSString *)account conference:(NSString *)conference receivedResponseToInvitationFrom: (NSDictionary*)buddyInfo properties: (NSDictionary*)props;
- (void) account: (NSString *)account conference:(NSString *)conference receivedCancelInvitationFrom: (NSDictionary*)buddyInfo properties: (NSDictionary*)props;
- (void) account: (NSString *)account conference:(NSString *)conference receivedCounterProposalFrom: (NSDictionary*)buddyInfo properties: (NSDictionary*)props;
- (void) account: (NSString *)account conference:(NSString *)conference receivedUpdateFrom: (NSDictionary*)buddyInfo data: (NSData*)info;
- (void) account: (NSString *)account conference: (NSString *)conference receivedAVMessage: (uint32_t) messageType from: (NSDictionary*)buddyInfo sessionID: (uint32_t) sessionID userInfo: (NSDictionary *) userInfo;
- (void) account: (NSString *)account conference:(NSString *)conference changedToNewConferenceID:(NSString *)newConferenceID;
- (void) account: (NSString *)account conference:(NSString *)conference peerIDChangedFromID:(NSString *)oldOld toID:(NSString *)newID;
- (void) account: (NSString *)account conference:(NSString *)conference peerID:(NSString *)peer propertiesUpdated:(NSDictionary *)properties;
- (void) account: (NSString *)account conference:(NSString *)conference invitationSentSuccessfully:(BOOL)success;
- (void) account:(NSString *)account avAction:(unsigned int)action withArguments:(NSDictionary *)arguments toAVChat:(NSString *)avChat isVideo:(BOOL)isVideo;
- (void) showInvalidCertNotificationForAccount: (NSString *) account;
- (void) showForgotPasswordNotificationForAccount:(NSString *) account;
- (void) property: (NSString*)propertyName changedTo:(id)value from:(id)oldValue;
- (void) persistentProperty: (NSString*)propertyName changedTo:(id)value from:(id)oldValue;
- (void) account:(NSString *)account statusChanged: (NSDictionary*)status;
- (void) account:(NSString *)account postedError:(NSError *)error;
- (void) account:(NSString *)account relay:(NSString *)relay handleInitate:(NSDictionary *)dictionary fromPerson:(NSDictionary *)personInfo;
- (void) account:(NSString *)account relay:(NSString *)relay handleUpdate:(NSDictionary *)dictionary fromPerson:(NSDictionary *)personInfo;
- (void) account:(NSString *)account relay:(NSString *)relay handleCancel:(NSDictionary *)dictionary fromPerson:(NSDictionary *)personInfo;
- (void) databaseUpdated;
- (void) databaseUpdated:(NSString *)stamp;
- (void) databaseFull;
- (void) databaseNoLongerFull;
- (void) databaseChatSpamUpdated:(NSString *)chatGUID;
- (void) unreadCountChanged:(NSInteger)unreadCount;
- (void) lastFailedMessageDateChanged:(int64_t)failedDate;
- (void) displayPinCodeForAccount:(NSString *)account pinCode:(NSNumber *)pinCode deviceName:(NSString *)deviceName deviceType:(NSString *)deviceType phoneNumber:(NSString*)phoneNumber;
- (void) pinCodeAlertCompleted:(NSString *)account deviceName:(NSString *)deviceName deviceType:(NSString *)deviceType phoneNumber:(NSString*)phoneNumber responseFromDevice:(BOOL)responseFromDevice wasCancelled:(BOOL)wasCancelled;
-(void) stickerPackUpdated:(NSDictionary *)stickerPackDictionary;
-(void) stickerPackRemoved:(NSArray *)stickerPackGUID;
- (void) updateCloudKitState;
- (void) updateCloudKitStateWithDictionary:(NSDictionary*) stateDictionary;
- (void) didAttemptToSetEnabledTo:(BOOL)targetEnabled result:(BOOL)didSucceed;
- (void) didPerformAdditionalStorageRequiredCheckWithSuccess:(BOOL)didSucceed additionalStorageRequired:(uint64_t) additionalStorageRequired forAccountId: (NSString*) iCloudAccountId error:(NSError*) error;
- (void) didAttemptToDisableAllDevicesResult:(BOOL)didSucceed;

- (void) didFetchSyncStateStats:(NSDictionary*) stats;
- (void) didAttemptToDisableiCloudBackups:(NSInteger) result error:(NSError* _Nullable) error;
- (void)oneTimeCodesDidChange:(NSArray <NSDictionary *>*)validOneTimeCodes;
- (void)receivedUrgentRequestForMessages:(NSArray<NSString *> *)messageGUIDs;
- (void)didFetchCloudKitSyncDebuggingInfo:(NSDictionary*) info;
- (void) lastMessageForAllChats:(NSDictionary *)chatIDToLastMessageDictionary;

- (void) groupPhotoUpdatedForChatIdentifier:(NSString*)chatIdentifier style:(IMChatStyle)style account:(NSString*)account userInfo:(NSDictionary*)userInfo;
@end

typedef id<IMDaemonListenerProtocol> FZDaemonListenerRef;

