//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class DDScannerResult, IMBalloonPluginDataSource, NSArray, NSAttributedString, NSData, NSDate, NSDictionary, NSString, NSURL;
@class IMMessage, IMMessageItem;

@interface IMPluginPayload : NSObject
{
    BOOL _update;
    BOOL _sticker;
    BOOL _shouldExpire;
    BOOL _isPlayed;
    BOOL _isFromMe;
    NSAttributedString *_text;
    NSData *_data;
    NSURL *_url;
    NSString *_breadcrumbText;
    NSString *_statusText;
    NSDictionary *_userInfo;
    NSString *_messageGUID;
    NSDate *_time;
    NSString *_associatedMessageGUID;
    NSString *_pluginBundleID;
    NSArray *_consumedSessionPayloads;
    NSString *_pluginSessionGUID;
    DDScannerResult *_dataDetectedResult;
    NSArray *_attachments;
    IMBalloonPluginDataSource *_datasource;
    NSString *_sender;
}

+ (BOOL)supportsSecureCoding;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(nonatomic) BOOL isFromMe; // @synthesize isFromMe=_isFromMe;
@property(nonatomic) __weak IMBalloonPluginDataSource *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) NSArray<NSURL*> *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) DDScannerResult *dataDetectedResult; // @synthesize dataDetectedResult=_dataDetectedResult;
@property(retain, nonatomic) NSString *pluginSessionGUID; // @synthesize pluginSessionGUID=_pluginSessionGUID;
@property(nonatomic) BOOL isPlayed; // @synthesize isPlayed=_isPlayed;
@property(retain, nonatomic) NSArray *consumedSessionPayloads; // @synthesize consumedSessionPayloads=_consumedSessionPayloads;
@property(retain, nonatomic) NSString *pluginBundleID; // @synthesize pluginBundleID=_pluginBundleID;
@property(retain, nonatomic) NSString *associatedMessageGUID; // @synthesize associatedMessageGUID=_associatedMessageGUID;
@property(retain, nonatomic) NSDate *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *messageGUID; // @synthesize messageGUID=_messageGUID;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) BOOL shouldExpire; // @synthesize shouldExpire=_shouldExpire;
@property(nonatomic, getter=isSticker) BOOL sticker; // @synthesize sticker=_sticker;
@property(nonatomic, getter=isUpdate) BOOL update; // @synthesize update=_update;
@property(retain, nonatomic) NSString *statusText; // @synthesize statusText=_statusText;
@property(retain, nonatomic) NSString *breadcrumbText; // @synthesize breadcrumbText=_breadcrumbText;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSAttributedString *text; // @synthesize text=_text;
- (instancetype)copyWithZone:(struct _NSZone *)arg1;
- (instancetype)initWithCoder:(id)arg1 additionalAllowedClasses:(id)arg2;
- (instancetype)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (BOOL)isEqualToPluginPayload:(id)arg1;
@property(readonly, nonatomic) BOOL shouldHideAttachments;
- (void)addAttachmentsFromFilePaths:(id)arg1;
- (void)addAttachmentsFromFileTransferGUIDs:(id)arg1;
- (instancetype)initWithMessageItem:(IMMessageItem*)arg1;
- (instancetype)initWithMessage:(IMMessage*)arg1;
- (NSString*) threadIdentifier API_AVAILABLE(macos(10.16), ios(14.0), watchos(7.0));

@end

