//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IMServiceImpl;

@interface IMService: NSObject
+ (IMServiceImpl*)smsService NS_SWIFT_NAME(sms());
+ (IMServiceImpl*)iMessageService NS_SWIFT_NAME(iMessage());
+ (IMServiceImpl*)facetimeService NS_SWIFT_NAME(facetime());
+ (IMServiceImpl*)callService NS_SWIFT_NAME(call());
+ (IMServiceImpl*)jabberService NS_SWIFT_NAME(jabber());
+ (IMServiceImpl*)subnetService NS_SWIFT_NAME(subnet());
+ (IMServiceImpl*)aimService NS_SWIFT_NAME(aim());
@end

