//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSLock, NSObject, NSString;

@interface CPDistributedNotificationCenter : NSObject
{
    NSString *_centerName;
    NSLock *_lock;
    struct __CFRunLoopSource *_receiveNotificationSource;
    BOOL _isServer;
    struct __CFDictionary *_sendPorts;
    unsigned long long _startCount;
    NSObject *_queue;
}

+ (instancetype _Nonnull)centerForServerPort:(unsigned int)arg1;
+ (void)setCenter:(id)arg1 forServerPort:(unsigned int)arg2;
+ (struct __CFDictionary *)_serverPortToNotificationCenterMap;
+ (id)_serverPortToNotificationCenterMapDispatchQueue;
+ (instancetype _Nonnull)centerNamed:(NSString* _Nonnull)arg1;
- (void)_receivedCheckIn:(unsigned int)arg1 auditToken:(id)arg2;
- (BOOL)postNotificationName:(NSString* _Nonnull)arg1 userInfo:(id _Nullable)arg2 toBundleIdentifier:(NSString* _Nonnull)arg3;
- (void)postNotificationName:(NSString* _Nonnull)arg1 userInfo:(id _Nullable)arg2;
- (void)postNotificationName:(NSString* _Nonnull)arg1;
- (void)runServer;
- (void)runServerOnCurrentThread;
- (void)deliverNotification:(id)arg1 userInfo:(id)arg2;
- (void)stopDeliveringNotifications;
- (void)startDeliveringNotificationsToRunLoop:(struct __CFRunLoop *)arg1;
- (void)startDeliveringNotificationsToMainThread;
- (void)_notificationServerWasRestarted;
- (void)_checkOutAndRemoveSource;
- (void)_checkIn;
- (void)_createReceiveSourceForRunLoop:(struct __CFRunLoop *)arg1;
- (NSString* _Nonnull)name;
- (void)dealloc;
- (instancetype _Nonnull)_initWithServerName:(NSString* _Nonnull)arg1;

@end

