//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>

@class NSString;

@interface CPExclusiveLock : NSObject
{
    int _fd;
    NSString *_name;
}

- (id)name;
- (void)setName:(id)arg1;
- (BOOL)tryLock;
- (void)unlock;
- (void)lock;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)init;

@end

