//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IDSDataChannelLinkContext, NSData, NSMutableArray, NSMutableDictionary, NSObject;

@interface _IDSDatagramChannel : NSObject
{
    BOOL _verboseFunctionalLogging;
    int _socketDescriptor;
    id _eventHandler;
    id _readHandler;
    id _readHandlerWithOptions;
    BOOL _connected;
    struct os_unfair_lock_s _writeLock;
    struct os_unfair_lock_s _readLock;
    BOOL _isInvalidated;
    NSObject *_connection;
    BOOL _hasMetadata;
    BOOL _sentFirstReadLinkInfo;
    BOOL _receivedPreConnectionData;
    BOOL _waitForPreConnectionDataForConnected;
    BOOL _startCalled;
    BOOL _startAutomatically;
    int _osChannelFD;
    NSObject *_pathEvaluator;
    struct channel *_osChannel;
    struct channel_ring_desc *_osChannelTXRing;
    struct channel_ring_desc *_osChannelRXRing;
    unsigned char _nexus_instance[16];
    IDSDataChannelLinkContext *_cellularLink;
    NSMutableDictionary *_linkContexts;
    BOOL _defaultLinkID;
    NSData *_preConnectionData;
    NSMutableArray *_sendingMetadata;
    BOOL _needsMediaEncryptionInfo;
    unsigned long long _outgoingBytes;
    unsigned long long _incomingBytes;
    double _lastOutgoingStatReport;
    double _lastIncomingStatReport;
    NSMutableDictionary *_MKIArrivalTime;
    NSMutableDictionary *_firstPacketArrivalTimeForMKI;
}


- (id)init;

@end

