//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "IDSDaemonListenerProtocol.h"

@class IDSDaemonRequestTimer, NSString;

@interface IDSAppleCareDaemonResponseListener : NSObject
{
    IDSDaemonRequestTimer *_requestTimer;
    id _disconnectedBlock;
}


- (void)daemonDisconnected;
- (void)applecareResponseForRequestID:(id)arg1 withError:(id)arg2;
- (id)initWithDisconnectedBlockAndNoTimeout:(id)arg1;
- (id)initWithRequestTimer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

