//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject, NSProtocolChecker;

@interface IDSDaemonControllerForwarder : NSProxy
{
    NSProtocolChecker *_protocol;
    id _completion;
    NSObject *_ivarQueue;
    NSObject *_remoteMessageQueue;
    int _priority;
}


@property(nonatomic) int priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) NSObject *remoteMessageQueue; // @synthesize remoteMessageQueue=_remoteMessageQueue;
@property(readonly, nonatomic) NSObject *ivarQueue; // @synthesize ivarQueue=_ivarQueue;
@property(readonly, nonatomic) id completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) NSProtocolChecker *protocol; // @synthesize protocol=_protocol;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)initWithProtocol:(id)arg1 ivarQueue:(id)arg2 remoteMessageQueue:(id)arg3 completion:(id)arg4;
- (id)initWithProtocol:(id)arg1 ivarQueue:(id)arg2 remoteMessageQueue:(id)arg3;

@end

