//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IDSDaemonResponseHandler, IMTimer;

@interface IDSDaemonRequestContext : NSObject
{
    IDSDaemonResponseHandler *_responseHandler;
    id _timeoutBlock;
    IMTimer *_systemTimer;
}


- (void)killSystemTimer;
- (id)systemTimer;
- (id)timeoutBlock;
- (id)responseHandler;
- (id)initWithResponseHandler:(id)arg1 timeoutBlock:(id)arg2 systemTimer:(id)arg3;
- (void)dealloc;

@end

