//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface IDSURI: NSObject
//+ (instancetype _Nonnull) URIWithPrefixedURI:(NSString*)uri;
- (nullable instancetype)initWithPrefixedURI:(NSString *)prefixedURI;
- (nullable instancetype)initWithUnprefixedURI:(NSString *)unprefixedURI;
@property (nonatomic, readonly, strong) NSString *prefixedURI;
@property (nonatomic, readonly, strong) NSString *unprefixedURI;
@end

@interface IDSDestination: NSObject
+ (id)destinationWithRapportPublicIdentifier:(id)arg1;
+ (id)destinationWithDevice:(id)arg1;
+ (instancetype _Nonnull) destinationWithURI:(NSString*)uri;
- (IDSURI* _Nonnull) uri;
@end

