//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableDictionary;

@interface IDSDaemonRequestTimer : NSObject
{
    NSMutableDictionary *_requestContextMap;
    struct _opaque_pthread_mutex_t _requestContextMapLock;
}


- (id)invalidateTimeoutsAndReturnHandlersForAllRequests;
- (id)_criticalInvalidateTimeoutAndReturnHandlerForRequestID:(id)arg1;
- (id)invalidateTimeoutAndReturnHandlerForRequestID:(id)arg1;
- (void)_criticalInvokeTimeoutBlockForRequestID:(id)arg1;
- (void)_handleSystemTimerFired:(id)arg1;
- (id)_criticalFindRequestContextWithResponseHandler:(id)arg1;
- (id)scheduleTimeoutWithResponseHandler:(id)arg1 timeoutInterval:(double)arg2 timeoutBlock:(id)arg3;
- (long long)inFlightRequestCount;
- (id)init;
- (void)dealloc;
- (void)_accessRequestContextMapInCriticalSectionWithBlock:(id)arg1;

@end

