//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IDSDataChannelLinkContext, NSArray, _IDSDatagramChannel;

@interface IDSDatagramChannel : NSObject
{
    _IDSDatagramChannel *_internal;
}

+ (id)realTimeContext;

- (void)osChannelInfoLog;
- (void)generateMetadataWithDatagramInfo:(id)arg1 options:(id)arg2 currentDatagramCount:(unsigned char)arg3 totalDatagramCount:(unsigned char)arg4 byteBuffer:(id)arg5;
- (void)_reportFirstPacketTimeForMKI:(id)arg1;
- (void)reportFirstPacketTimeForMKI:(id)arg1;
- (void)requestSessionInfoWithOptions:(id)arg1;
- (void)stopActiveProbingOnLinks:(id)arg1;
- (void)startActiveProbingOnLinks:(id)arg1 interval:(unsigned int)arg2 timeout:(unsigned int)arg3;
- (void)setWiFiAssist:(BOOL)arg1;
- (id )_setWiFiAssist:(BOOL)arg1;
- (void)setChannelPreferences:(id)arg1;
- (void)_buildPacketBufferMetaData:(id)arg1;
- (void)sendMetadata;
- (void)readyToRead;
- (void)setReadHandlerWithOptions:(id)arg1;
- (void)setReadHandler:(id)arg1;
- (void)setEventHandler:(id)arg1;
- (void)writeDatagram:(const void *)arg1 datagramSize:(unsigned int)arg2 datagramInfo:(id)arg3 options:(id)arg4 completionHandler:(id)arg5;
- (void)writeDatagram:(const void *)arg1 datagramSize:(unsigned int)arg2 flags:(id)arg3 completionHandler:(id)arg4;
- (void)_writeDatagram:(const void *)arg1 datagramSize:(unsigned int)arg2 datagramInfo:(id)arg3 options:(id)arg4 completionHandler:(id)arg5;
- (void)writeDatagrams:(const void **)arg1 datagramSizes:(unsigned int *)arg2 datagramInfo:(id)arg3 datagramCount:(int)arg4 options:(id)arg5 completionHandler:(id)arg6;
- (void)writeDatagrams:(const void **)arg1 datagramsSize:(unsigned int *)arg2 datagramsInfo:(id)arg3 datagramsCount:(int)arg4 options:(id)arg5 completionHandler:(id)arg6;
- (void)start;
- (void)invalidate;
- (void)close;
- (void)readDatagramsWithCompletionHandler:(id)arg1;
- (void)readDatagramWithCompletionHandler:(id)arg1;
- (void)processMetadataForDatagram:(char *)arg1 size:(unsigned long long)arg2 datagramInfo:(id)arg3 options:(id)arg4;
- (void)sendMediaMembershipChangedInfo:(unsigned char)arg1;
- (void)sendMediaEncryptionInfoWithMKM:(id)arg1 MKS:(id)arg2 MKI:(id)arg3 isLocallyGenerated:(BOOL)arg4;
- (void)selectDefaultLink:(BOOL)arg1;
- (void)addNewIDSDataChannelLinkWithAttributes:(char *)arg1 linkAttributesLength:(unsigned short)arg2;
- (void)removeIDSDataChannelLinkContext:(BOOL)arg1 linkUUID:(id)arg2;
- (void)sendEventConnectedWithDummyLinkInfo;
- (int)underlyingFileDescriptor;
- (void)_logReceivingStats:(unsigned long long)arg1;
- (void)_logSendingStats:(unsigned long long)arg1;
- (id)description;
- (void)dealloc;
- (id)cachedMetadata;
- (id)initWithDestination:(id)arg1;
- (id)initWithSocketDescriptor:(int)arg1;
@property(readonly) IDSDataChannelLinkContext *defaultLink;
@property(readonly) NSArray *connectedLinks;

@end

