//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject;

@protocol IDSInternalQueueController <NSObject>
//{
//    NSObject *_queue;
//    void *_contextKey;
//}

+ (id<IDSInternalQueueController>)sharedInstance;

- (id)queue;
- (BOOL)isQueueCurrent;
- (void)assertQueueIsNotCurrent;
- (void)assertQueueIsCurrent;
- (void)performBlock:(id)arg1 waitUntilDone:(BOOL)arg2;
- (void)performBlock:(id)arg1;
- (id)initWithQueue:(id)arg1;
- (id)initWithName:(char *)arg1 contextKey:(void *)arg2;
- (id)init;

@end

