//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class IDSXPCDaemonController;

@interface IDSPhoneSubscriptionSelector : NSObject
{
    id _syncDaemonController;
    id _syncDaemonControllerBuilder;
}


@property(copy, nonatomic) id syncDaemonControllerBuilder; // @synthesize syncDaemonControllerBuilder=_syncDaemonControllerBuilder;
@property(retain, nonatomic) IDSXPCDaemonController *syncDaemonController; // @synthesize syncDaemonController=_syncDaemonController;
- (void)_performSyncAction:(id)arg1;
- (id)setSelectedSubscriptions:(id)arg1 withError:(id )arg2;
- (id)unselectSubscription:(id)arg1 withError:(id )arg2;
- (id)selectSubscription:(id)arg1 withError:(id )arg2;
- (id)selectedSubscriptionsWithError:(id )arg1;
- (void)setSelectedSubscriptions:(id)arg1 withCompletion:(id)arg2;
- (void)unselectSubscription:(id)arg1 withCompletion:(id)arg2;
- (void)selectSubscription:(id)arg1 withCompletion:(id)arg2;
- (void)requestSelectedSubscriptionsWithCompletion:(id)arg1;
- (id)initWithSyncDaemonControllerBuilder:(id)arg1;
- (id)init;

@end

