//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "IDSAccountControllerDelegate.h"
#import "IDSAccountRegistrationDelegate.h"

@class IDSCTAdapter, NSMapTable, NSMutableDictionary, NSObject, NSString;

@interface IDSSignInController : NSObject
{
    NSMutableDictionary *_serviceNameAccountControllerMap;
    NSMutableDictionary *_accountIDDescriptionMap;
    NSMapTable *_delegateByServiceType;
    NSMutableDictionary *_initialStateByService;
    NSObject *_signInQueue;
    id _passwordManager;
    double _signInTimeout;
    double _signInFuzz;
    IDSCTAdapter *_CTAdapter;
}


@property(retain, nonatomic) IDSCTAdapter *CTAdapter; // @synthesize CTAdapter=_CTAdapter;
@property(retain, nonatomic) NSMutableDictionary *initialStateByService; // @synthesize initialStateByService=_initialStateByService;
@property(retain, nonatomic) NSMapTable *delegateByServiceType; // @synthesize delegateByServiceType=_delegateByServiceType;
@property(nonatomic) double signInFuzz; // @synthesize signInFuzz=_signInFuzz;
@property(nonatomic) double signInTimeout; // @synthesize signInTimeout=_signInTimeout;
@property(retain, nonatomic) id passwordManager; // @synthesize passwordManager=_passwordManager;
@property(retain, nonatomic) NSObject *signInQueue; // @synthesize signInQueue=_signInQueue;
@property(retain, nonatomic) NSMutableDictionary *accountIDDescriptionMap; // @synthesize accountIDDescriptionMap=_accountIDDescriptionMap;
@property(retain, nonatomic) NSMutableDictionary *serviceNameAccountControllerMap; // @synthesize serviceNameAccountControllerMap=_serviceNameAccountControllerMap;
- (void)accountController:(id)arg1 accountRemoved:(id)arg2;
- (void)accountController:(id)arg1 accountDisabled:(id)arg2;
- (void)accountController:(id)arg1 accountAdded:(id)arg2;
- (void)refreshRegistrationForAccount:(id)arg1;
- (void)_validateDelegateState;
- (unsigned long long)_serviceTypeForName:(id)arg1;
- (id)_serviceNameForType:(unsigned long long)arg1;
- (id)_accountWithUniqueID:(id)arg1;
- (id)_accountControllerForName:(id)arg1;
- (id)_createAccountControllerForService:(id)arg1;
- (BOOL)_actionOnAccountOfType:(unsigned long long)arg1 onService:(unsigned long long)arg2 actionBlock:(id)arg3;
- (unsigned long long)_statusOfAccount:(id)arg1;
- (id)_createAccountWithDictionary:(id)arg1 accountID:(id)arg2 serviceName:(id)arg3;
- (void)_validateStateForAccountID:(id)arg1 timeoutMode:(unsigned long long)arg2;
- (void)_cleanupStateForAccountID:(id)arg1;
- (void)_scheduleValidationAfter:(double)arg1 forAccountID:(id)arg2 allowFuzz:(BOOL)arg3;
- (void)_initializeStateMachineForAccountID:(id)arg1 service:(id)arg2 state:(unsigned long long)arg3 completion:(id)arg4;
- (void)signOutService:(unsigned long long)arg1 completion:(id)arg2;
- (void)signInUsername:(id)arg1 withProvidedCredential:(id)arg2 onService:(unsigned long long)arg3 waitUntilRegistered:(BOOL)arg4 completion:(id)arg5;
- (void)signInUsername:(id)arg1 onService:(unsigned long long)arg2 waitUntilRegistered:(BOOL)arg3 withCompletion:(id)arg4;
- (void)provideCredential:(id)arg1 forUser:(id)arg2 onService:(unsigned long long)arg3 withCompletion:(id)arg4;
- (void)statusOfUsersOnService:(unsigned long long)arg1 withCompletion:(id)arg2;
- (id)_statusOfUsersOnService:(unsigned long long)arg1;
- (void)disableUserType:(unsigned long long)arg1 onService:(unsigned long long)arg2 completion:(id)arg3;
- (void)enableUserType:(unsigned long long)arg1 onService:(unsigned long long)arg2 completion:(id)arg3;
- (void)removeDelegateForService:(unsigned long long)arg1;
- (void)setDelegate:(id)arg1 forService:(unsigned long long)arg2;
- (id)init;
- (id)initWithQueue:(id)arg1;
- (id)initWithPasswordManager:(id)arg1 CTAdapter:(id)arg2 signInTimeout:(double)arg3 signInFuzz:(double)arg4 queue:(id)arg5;
- (BOOL)_isServiceCurrentlyEnabled:(id)arg1;
- (BOOL)isiMessageEnabled;
- (BOOL)isFaceTimeEnabled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

