//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface IDSTransactionLogTask : NSObject
{
    id _completionBlock;
}


@property(copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
- (void)_completeWithError:(id)arg1;

@end

