//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IDSTransactionLogTaskHandler, NSArray, NSSet;

@protocol IDSTransactionLogTaskHandlerDelegate
- (void)taskHandler:(IDSTransactionLogTaskHandler *)arg1 accountInfoForAliases:(NSSet *)arg2 completion:(void (^)(id, NSError *))arg3;
- (void)persistedTokenForTaskHandler:(IDSTransactionLogTaskHandler *)arg1 completion:(void (^)(id, NSError *))arg2;
- (void)taskHandler:(IDSTransactionLogTaskHandler *)arg1 persistToken:(id)arg2 completion:(void (^)(NSError *))arg3;
- (void)taskHandler:(IDSTransactionLogTaskHandler *)arg1 messagesFromToken:(id)arg3;
- (void)taskHandler:(IDSTransactionLogTaskHandler *)arg1 participantsWithDestinations:(NSArray *)arg2 completion:(void (^)(NSArray *, NSError *))arg3;
- (void)taskHandler:(IDSTransactionLogTaskHandler *)arg1 groupsWithGroupIDs:(NSArray *)arg2 completion:(void (^)(NSArray *, NSError *))arg3;
@end

