//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDS/IDSTransactionLogTaskHandler.h>

@class IDSTransactionLogTask, NSObject;

@interface IDSTransactionLogBaseTaskHandler : IDSTransactionLogTaskHandler
{
    IDSTransactionLogTask *_task;
    NSObject *_queue;
}


@property(retain, nonatomic) NSObject *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) IDSTransactionLogTask *task; // @synthesize task=_task;
- (void)perform;
- (id)initWithTask:(id)arg1 delegate:(id)arg2 queue:(id)arg3;

@end

