//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol IDSXPCDaemon
- (void)interalTestingCollaboratorWithCompletion:(void (^)(id, NSError *))arg1;
- (void)registrationCollaboratorWithCompletion:(void (^)(id, NSError *))arg1;
- (void)opportunisticCollaboratorWithCompletion:(void (^)(id, NSError *))arg1;
- (void)reunionSyncCollaboratorForClientProcessName:(NSString *)arg1 withCompletion:(void (^)(id, NSError *))arg2;
- (void)pairedDeviceManagerCollaboratorWithCompletion:(void (^)(id, NSError *))arg1;
- (void)pairingCollaboratorWithCompletion:(void (^)(id, NSError *))arg1;
- (void)activateWithCompletion:(void (^)(NSError *))arg1;
@end

