//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class LPPadding;


@interface LPCaptionBarAccessoryStyle : NSObject
{
    LPPadding *_margin;
}


@property(readonly, retain, nonatomic) LPPadding *margin; // @synthesize margin=_margin;
- (id)init;

@end

