//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPHTMLComponent.h>


@interface LPEmailCompatibleHTMLInnerLinkComponent : LPHTMLComponent
{
}

- (id)initWithThemePath:(id)arg1 generator:(id)arg2;

@end

