//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class LPFetcherConfiguration, NSMutableArray;


@interface LPFetcherGroup : NSObject
{
    LPFetcherConfiguration *_configuration;
    long long _responsePolicy;
    id _completionHandler;
    NSMutableArray *_tasks;
    BOOL _doneAddingFetchers;
    BOOL _done;
    unsigned int _loggingID;
}


- (void)_completed;
- (void)cancel;
- (id)_responsesRespectingPolicy;
- (void)evaluateCompleteness;
- (void)doneAddingFetchers;
- (void)startFetchesIfNeeded;
- (unsigned long long)numberOfActiveFetches;
- (void)prependFetcher:(id)arg1;
- (void)appendFetcher:(id)arg1;
- (void)_addFetcher:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)initWithPolicy:(long long)arg1 configuration:(id)arg2 completionHandler:(id)arg3;

@end

