//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPFetcherResponse.h>

@class LPAudio;


@interface LPFetcherAudioResponse : LPFetcherResponse
{
    LPAudio *_audio;
}

+ (id)audioPropertiesForFetcher:(id)arg1;

@property(readonly, retain, nonatomic) LPAudio *audio; // @synthesize audio=_audio;
- (id)initWithAudio:(id)arg1 fetcher:(id)arg2;

@end

