//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPFetcherResponse.h>

@class NSString;


@interface LPFetcherStringResponse : LPFetcherResponse
{
    NSString *_string;
}


@property(readonly, copy, nonatomic) NSString *string; // @synthesize string=_string;
- (id)initWithString:(id)arg1 fetcher:(id)arg2;

@end

