//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface LPImagePresentationProperties : NSObject
{
    BOOL _shouldApplyBackground;
    BOOL _requireFixedSize;
    long long _filter;
    long long _scalingMode;
    id _backgroundColor;
    id _maskColor;
}


@property(retain, nonatomic) id maskColor; // @synthesize maskColor=_maskColor;
@property(retain, nonatomic) id backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) BOOL requireFixedSize; // @synthesize requireFixedSize=_requireFixedSize;
@property(nonatomic) BOOL shouldApplyBackground; // @synthesize shouldApplyBackground=_shouldApplyBackground;
@property(nonatomic) long long scalingMode; // @synthesize scalingMode=_scalingMode;
@property(nonatomic) long long filter; // @synthesize filter=_filter;
- (id)init;

@end

