//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface LPImageProperties : NSObject
{
    NSString *_accessibilityText;
    long long _type;
    id _overlaidTextColor;
}


@property(retain, nonatomic) id overlaidTextColor; // @synthesize overlaidTextColor=_overlaidTextColor;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *accessibilityText; // @synthesize accessibilityText=_accessibilityText;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

