//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;


@interface LPiTunesMediaLookupTask : NSObject
{
    NSString *_identifier;
    NSString *_storefrontCountryCode;
}


- (void)start:(id)arg1;
- (id)_compileQueryParametersWithBundleIds:(id)arg1 itemIds:(id)arg2;
- (id)initWithIdentifier:(id)arg1 storefrontCountryCode:(id)arg2;
- (id)callerID;
- (id)sharedBag;

@end

