//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class LPMetadataProviderSpecializationContext, NSURL;


@interface LPMetadataProviderSpecialization : NSObject
{
    id _delegate;
    LPMetadataProviderSpecializationContext *_context;
}

+ (unsigned long long)specialization;
+ (BOOL)generateSpecializedMetadataForCompleteMetadata:(id)arg1 withContext:(id)arg2 completionHandler:(id)arg3;
+ (id)specializedMetadataProviderForMetadata:(id)arg1 withContext:(id)arg2;
+ (id)specializedMetadataProviderForResourceWithContext:(id)arg1;
+ (id)specializedMetadataProviderForURLWithContext:(id)arg1;

@property(readonly, nonatomic) LPMetadataProviderSpecializationContext *context; // @synthesize context=_context;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSURL *URL;
- (void)cancel;
- (void)start;
- (id)initWithContext:(id)arg1;

@end

