//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPComponentView.h>

#import "LPContentInsettable.h"

@class LPMusicPlayButtonStyle;


@interface LPPlayButtonView : LPComponentView <LPContentInsettable>
{
    struct NSEdgeInsets _contentInset;
    LPMusicPlayButtonStyle *_style;
}


- (void)setContentInset:(struct NSEdgeInsets)arg1;
- (id)initWithPlaybackInformation:(id)arg1 style:(id)arg2;

@end

