//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>

@class LPPointUnit;


@interface LPSize : NSObject
{
    LPPointUnit *_width;
    LPPointUnit *_height;
}


@property(readonly, retain, nonatomic) LPPointUnit *height; // @synthesize height=_height;
@property(readonly, retain, nonatomic) LPPointUnit *width; // @synthesize width=_width;
@property(readonly, nonatomic, getter=isEmpty) BOOL empty;
@property(readonly, nonatomic) struct CGSize asSize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSquareSize:(double)arg1;
- (id)initWithSize:(struct CGSize)arg1;
- (id)init;

@end

