//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPVideoView.h>

@class AVPlayerLayer, AVPlayerLooper, AVQueuePlayer;


@interface LPStreamingVideoView : LPVideoView
{
    AVQueuePlayer *_player;
    AVPlayerLooper *_looper;
    AVPlayerLayer *_playerLayer;
    id _readyForDisplayCallback;
    BOOL _hasCreatedVideoPlayerView;
    BOOL _isWaitingToRetryAfterFailingToPlay;
    unsigned int _playbackRetryCountWithoutSuccess;
    BOOL _desiredPlayingState;
    float _desiredVolume;
}


- (void)prepareForDisplayWithCompletionHandler:(id)arg1;
- (id)createVideoPlayerView;
- (void)layoutComponentView;
- (void)setVolume:(double)arg1;
- (double)volume;
- (void)setMuted:(BOOL)arg1;
- (BOOL)isMuted;
- (BOOL)shouldShowMuteButton;
- (BOOL)usesSharedAudioSession;
- (BOOL)shouldAutoPlay;
- (BOOL)releaseDecodingResourcesIfInactive;
- (void)setPlaying:(BOOL)arg1;
- (void)didFailToPlay;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)resetToPlaceholderView;
- (void)destroyPlayer;
- (void)createPlayerIfNeeded;
- (void)createPlayerItemAdjustedForLoopingWithAsset:(id)arg1 completionHandler:(id)arg2;
- (void)dealloc;
- (id)initWithVideo:(id)arg1 style:(id)arg2 posterFrame:(id)arg3 posterFrameStyle:(id)arg4 configuration:(id)arg5;

@end

