//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <LinkPresentation/LPComponentView.h>

#import "CAAnimationDelegate.h"
#import <Foundation/Foundation.h>

@class LPTapToLoadViewStyle, LPTextView, NSPressGestureRecognizer, NSString, NSView;


@interface LPTapToLoadView : LPComponentView
{
    LPTextView *_captionView;
    NSView *_progressView;
    LPTapToLoadViewStyle *_style;
    NSView *_highlightView;
    NSPressGestureRecognizer *_highlightGestureRecognizer;
    BOOL _wasTapped;
    id _animateOutCompletionHandler;
    id _delegate;
}


@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animateOutWithCompletionHandler:(id)arg1;
- (void)_animateToProgressView;
- (void)_tapRecognized:(id)arg1;
- (void)_highlightLongPressRecognized:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)_createIndeterminateProgressIndicator;
- (void)_buildViews;
- (void)layoutComponentView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithStyle:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

