//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "WKScriptMessageHandler.h"

@class LPYouTubePlayerView, NSString;


@interface LPYouTubePlayerScriptMessageHandler : NSObject
{
    LPYouTubePlayerView *_playerView;
}


- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (id)initWithPlayerView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

