//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSItemProvider (LPExtras)
+ (id)_lp_itemProviderWithData:(id)arg1 MIMEType:(id)arg2;
- (void)_lp_loadFirstDataRepresentationMatchingMIMETypePredicate:(id)arg1 completionHandler:(id)arg2;
@end

