//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>

@class IMMessage;

@interface ArchivedMessagePlaceholder : NSObject
{
    IMMessage *_message;
}

+ (BOOL)supportsSecureCoding;
+ (id)allowedSecureArchivingClasses_so;

@property(readonly) IMMessage *message; // @synthesize message=_message;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMessage:(id)arg1;

@end

