//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class DOMElement, IMAssociatedMessageChatItem;

@protocol AssociatedMessageDOMProvider
- (void)parseAssociatedChatItem:(IMAssociatedMessageChatItem *)arg1 appendToElement:(DOMElement *)arg2 withChatItemElement:(DOMElement *)arg3;
@end

