//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSSplitViewController (SocialUIAdditions)
- (void)splitViewItem:(id)arg1 setCollapsed:(BOOL)arg2 withPriority:(float)arg3 resizeRatio:(double)arg4 animatedWithDuration:(double)arg5 completionBlock:(id)arg6;
@end

