//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>



@class CALayer, NSString;

@interface SONativeTranscriptHostView : NSObject
{
}

@property(readonly, nonatomic) struct CGRect gradientFrame;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly, nonatomic) CALayer *layer;
@property(readonly) Class superclass;

@end

