//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class SOTokenFieldCell;

@protocol SOTokenFieldCellDragDelegate
- (void)tokenFieldCellDidEndDropOperation:(SOTokenFieldCell *)arg1;
- (void)tokenFieldCellDidBeginDropOperation:(SOTokenFieldCell *)arg1;
@end

