//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "SOTranscriptThemeable.h"
#import "SOTranscriptCollectionViewItemDelegate.h"

@class IMTranscriptChatItem, NSLayoutConstraint, NSString;

@interface SOTranscriptCollectionViewItem : NSCollectionViewItem
{
    NSLayoutConstraint *_maxWidthConstraint;
    IMTranscriptChatItem *_chatItem;
    id _delegate;
    id _gradientReferenceView;
}

+ (id)itemTypeIdentifier;
+ (Class)viewClass;

@property(nonatomic) __weak id gradientReferenceView; // @synthesize gradientReferenceView=_gradientReferenceView;
@property __weak id delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id transcriptTheme;
- (void)prepareForReuse;
@property(readonly) struct IMBalloonDescriptor_t balloonDescriptor;
- (void)_transcriptItemDidChange;
- (struct CGSize)sizeConstrainedToWidth:(double)arg1;
@property(nonatomic) double maximumWidth;
- (long long)verticalSpaceToPrecedingItemOfClassification:(long long)arg1;
@property(readonly, nonatomic) long long layoutClassification;
@property(readonly, nonatomic) long long layoutOrientation;
- (void)loadView;
@property(retain, nonatomic) IMTranscriptChatItem *chatTranscriptItem;
@property(readonly, nonatomic) IMTranscriptChatItem *chatItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

