//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString, SOTranscriptEffectPicker;

@protocol SOTranscriptEffectPickerDelegate
- (void)effectPickerWasCancelled:(SOTranscriptEffectPicker *)arg1;
- (void)effectPicker:(SOTranscriptEffectPicker *)arg1 didPickEffect:(NSString *)arg2;
@end

