//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ETPointFIFO : NSObject
{
    ETPointFIFO *_nextFIFO;
}


@property(retain, nonatomic) ETPointFIFO *nextFIFO; // @synthesize nextFIFO=_nextFIFO;
- (void)clear;
- (void)flush;


- (id)initWithFIFO:(id)arg1;

@end

