//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DigitalTouchShared/ETPointFIFO.h>

@interface ETQuadCurvePointFIFO : ETPointFIFO
{
    BOOL _emitInterpolatedPoints;
    float _unitSize;
    id _emissionHandler;

    id _prevPoints;
    id _points;
    id _controlPoints;
}




// Property attributes: T,N,V_lastPoint

@property(nonatomic) id controlPoints; // @synthesize controlPoints=_controlPoints;
@property(nonatomic) id points; // @synthesize points=_points;
@property(nonatomic) id prevPoints; // @synthesize prevPoints=_prevPoints;
@property(copy) id emissionHandler; // @synthesize emissionHandler=_emissionHandler;
@property(nonatomic) BOOL emitInterpolatedPoints; // @synthesize emitInterpolatedPoints=_emitInterpolatedPoints;
@property(nonatomic) float unitSize; // @synthesize unitSize=_unitSize;
- (void)clear;
- (void)flush;

- (id)initWithFIFO:(id)arg1;

@end

