//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "DataDetectorsSourceAccessProtocol.h"

@interface DataDetectorsSourceAccess : NSObject
{

    int _clientpid;
    unsigned int _clientuid;
    BOOL _privacyUserReadEntitled;
    unsigned char _privacyUserReadEntitlementChecked;
    BOOL _privacyUserWriteEntitled;
    unsigned char _privacyUserWriteEntitlementChecked;
    BOOL _privacySystemWriteEntitled;
    unsigned char _privacySystemWriteEntitlementChecked;
}

@property unsigned int userIdentifier; // @synthesize userIdentifier=_clientuid;
@property int processIdentifier; // @synthesize processIdentifier=_clientpid;
 // @synthesize auditToken=_auditToken;
- (BOOL)pushSourcesContent:(id)arg1 forSource:(int)arg2 signature:(id)arg3;
- (BOOL)clientCanWriteSource:(int)arg1;
- (id)fileHandleForSourceRead:(int)arg1 resourceType:(unsigned long long)arg2;
- (BOOL)privacySystemWriteEntitled;
- (BOOL)privacyUserWriteEntitled;
- (BOOL)privacyUserReadEntitled;
- (void)writeSourceFromJSONFile:(id)arg1 source:(id)arg2 withReply:(id)arg3;
- (void)writeSourceFromRawData:(id)arg1 source:(id)arg2 signature:(id)arg3 withReply:(id)arg4;
- (void)filesForSourceRead:(id)arg1 resourceType:(unsigned long long)arg2 withReply:(id)arg3;
- (void)fileForSourceRead:(id)arg1 resourceType:(unsigned long long)arg2 withReply:(id)arg3;

@end

