//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableArray, NSMutableDictionary, NSObject;

__attribute__((visibility("hidden")))
@interface DDMessageCache : NSObject
{
    NSObject *_queue;
    NSObject *_memoryWarningSource;
    NSMutableDictionary *_cache;
    NSMutableArray *_indexLRU;
}


- (id)stringWithElement:(id)arg1 conversationID:(id)arg2 range:(struct _NSRange *)arg3;
- (void)removeConversation:(id)arg1;
- (void)_pruneIgnoringFirst:(BOOL)arg1;
- (id)init;

@end

