//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface DDScannerService : NSObject
{
}

+ (void)cancelJob:(long long)arg1;
+ (long long)scanString:(id)arg1 completionBlock:(void (^)(NSArray*))arg2;
+ (long long)scanQuery:(struct __DDScanQuery *)arg1 configuration:(id)arg2 completionBlock:(id)arg3;
+ (long long)scanString:(id)arg1 range:(struct _NSRange)arg2 configuration:(id)arg3 completionBlock:(id)arg4;
+ (id)scanString:(id)arg1;
+ (id)scanQuery:(struct __DDScanQuery *)arg1 configuration:(id)arg2;
+ (id)scanString:(id)arg1 range:(struct _NSRange)arg2 configuration:(id)arg3;
+ (void)appendWatchOSLinksToString:(id)arg1;

@end

