//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

__attribute__((visibility("hidden")))
@interface DDScanStepBlockContainer : NSObject
{
    id _block;
    long long _identifier;
}


@property(readonly, nonatomic) long long identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) id block; // @synthesize block=_block;
- (id)initWithBlock:(id)arg1 identifier:(long long)arg2;

@end

