//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableDictionary, NSObject;

__attribute__((visibility("hidden")))
@interface DDScanServerDispatcher : NSObject
{
    NSObject *_scannerQueue;
    NSObject *_workQueue;
    NSObject *_reportQueue;
    NSObject *_memoryWarningSource;
    BOOL _memoryWarningInProgress;
    NSMutableDictionary *_scanners;
    BOOL _tearDownRequested;
    unsigned long long _jobIdentifier;
}


- (void)dealloc;
- (void)recycleScanner:(id)arg1 fromList:(id)arg2 sameQueue:(BOOL)arg3;
- (void)cancelJob:(long long)arg1;
- (long long)scannerConf:(id)arg1 sync:(BOOL)arg2 shortTask:(BOOL)arg3 runTask:(id)arg4;
- (long long)emptyIdentifier;
- (BOOL)reachedMaxSimultaneousTask;
- (id)scannerListForConfiguration:(id)arg1;
- (id)reportQueue;
- (id)init;

@end

