//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreUI/CUIThemeSchema.h>

__attribute__((visibility("hidden")))
@interface _CUIMacOSThemeSchema : CUIThemeSchema
{
}

- (id)schemaTuplesWithAvailableAnimationsForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailableDimensionsForPart:(const id )arg1 withList:(id)arg2 isEffect:(BOOL)arg3;
- (id)schemaTuplesWithAvailableScalesForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailableDrawingLayersForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailableStatesForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailablePresentationStatesForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailableDirectionsForPart:(const id )arg1 withList:(id)arg2;
- (id)schemaTuplesWithAvailableValuesForPart:(const id )arg1 withList:(id)arg2 isEffect:(BOOL)arg3;
- (id)schemaTuplesWithAvailableSizesForPart:(const id )arg1 withList:(id)arg2;
- (id)defaultCoreUIOptionsForPartDefinition:(const id )arg1;
- (void)enumerateAvailableValuesForThemeAttribute:(int)arg1 inPartDefinition:(const id )arg2 usingBlock:(id)arg3;
- (void)enumerateAvailableThemeAttributesInPartDefinition:(const id )arg1 usingBlock:(id)arg2;
- (id)renditionsForSchemaTuples:(id)arg1;
- (id)schemaRenditionsForPartDefinition:(const id )arg1;
- (const id )partDefinitionForWidgetName:(id)arg1;
- (id)widgetNameForPartDefinition:(const id )arg1;
- (id)schemaEffectRenditionsForPartDefinition:(const id )arg1;
- (id)effectRenditionsForSchemaTuples:(id)arg1;
- (id)defaultCoreUIOptionsForEffectDefinition:(const id )arg1;
- (const id )effectDefinitionWithName:(id)arg1;
- (unsigned long long)effectDefinitionCount;
- (const id )sortedEffectDefinitionAtIndex:(unsigned long long)arg1;
- (const id )_sortedEffectDefinitions;
- (const id )effectDefinitionAtIndex:(unsigned long long)arg1;
- (id)schemaMaterialRenditionsForPartDefinition:(const id )arg1;
- (id)materialRenditionsForSchemaTuples:(id)arg1;
- (id)defaultCoreUIOptionsForMaterialDefinition:(const id )arg1;
- (const id )materialDefinitionWithName:(id)arg1;
- (unsigned long long)materialDefinitionCount;
- (const id )sortedMaterialDefinitionAtIndex:(unsigned long long)arg1;
- (const id )_sortedMaterialDefinitions;
- (const id )materialDefinitionAtIndex:(unsigned long long)arg1;
- (const id )categoryForElementDefinition:(const id )arg1;
- (const id )elementDefinitionWithName:(id)arg1;
- (unsigned long long)elementDefinitionCount;
- (const id )sortedElementDefinitionAtIndex:(unsigned long long)arg1;
- (const id )_sortedElementDefinitions;
- (const id )elementDefinitionAtIndex:(unsigned long long)arg1;
- (unsigned long long)elementCategoryCount;
- (const id )elementCategoryAtIndex:(unsigned long long)arg1;
- (long long)schemaVersion;

@end

