//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject;

@interface CUIRuntimeStatistics : NSObject
{





    NSObject *_queue;
    int _notify_token;
}

+ (void)generateLog;
+ (id)sharedRuntimeStatistics;
- (void)incrementMissedLookup;
- (void)incrementStatisticLookup;
- (void)incrementStatisticDidShortCircuitImageLookup;
- (void)addStatisticAllocatedImageSize:(unsigned long long)arg1 roundedSize:(unsigned long long)arg2;
- (void)_logStatistics:(int)arg1;
- (void)dealloc;
- (id)init;

@end

