//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPAsyncOperation.h>

@class MPMediaLibraryView;

@interface _MPModelLibraryRequestItemsQueryOperation : MPAsyncOperation
{
    MPMediaLibraryView *_libraryView;
    id _resultHandler;
    shared_ptr_34add297 _query;
}



@property(copy, nonatomic) id resultHandler; // @synthesize resultHandler=_resultHandler;
@property(nonatomic) shared_ptr_34add297 query; // @synthesize query=_query;
@property(retain, nonatomic) MPMediaLibraryView *libraryView; // @synthesize libraryView=_libraryView;
- (void)execute;

@end

