//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPModelSocialPerson, MPStoreSocialRequestOperation;
@protocol OS_dispatch_queue;

@interface _MPStoreSocialTransientState : NSObject
{
    long long _followState;
    long long _followPendingRequestState;
    NSObject *_accessQueue;
    NSObject *_calloutQueue;
    MPStoreSocialRequestOperation *_latestFollowOperation;
    MPStoreSocialRequestOperation *_latestFollowPendingRequestOperation;
    MPModelSocialPerson *_person;
    id _completionBlock;
}


@property(copy, nonatomic) id completionBlock; // @synthesize completionBlock=_completionBlock;
@property(readonly, nonatomic) MPModelSocialPerson *person; // @synthesize person=_person;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)_endIfNeeded;
- (id)newOperationForTransientFollowPendingRequestState:(long long)arg1 completion:(id)arg2;
@property(readonly, nonatomic) long long followPendingRequestState;
- (id)newOperationForTransientFollowState:(long long)arg1 completion:(id)arg2;
@property(readonly, nonatomic) long long followState;
- (id)initWithPerson:(id)arg1;

@end

