//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPAsyncOperation.h>

@class MPMediaLibraryView;

@interface _MPStoreLibraryPersonalizationAggregateLibraryAddedOperation : MPAsyncOperation
{
    MPMediaLibraryView *_libraryView;
    id _responseHandler;
    id bbba3654 _persistentIDs;
}



@property(copy, nonatomic) id responseHandler; // @synthesize responseHandler=_responseHandler;
@property(nonatomic) id bbba3654 persistentIDs; // @synthesize persistentIDs=_persistentIDs;
@property(nonatomic) MPMediaLibraryView *libraryView; // @synthesize libraryView=_libraryView;
- (void)execute;

@end

