//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPAsyncOperation.h>

@interface MPAsyncBlockOperation : MPAsyncOperation
{
    id _startHandler;
}


@property(readonly, copy, nonatomic) id startHandler; // @synthesize startHandler=_startHandler;
- (void)execute;
- (id)initWithStartHandler:(id)arg1;

@end

