//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface MPAVRouteConnection : NSObject
{
    NSObject *_accessQueue;
    NSObject *_calloutQueue;
    _Bool _invalidated;
    NSMutableArray *_pendingConnectionHandlers;
    id _receivedCustomDataHandler;
    id _invalidationHandler;
    void *_externalDevice;
}


@property(readonly, nonatomic) void *externalDevice; // @synthesize externalDevice=_externalDevice;
@property(copy, nonatomic) id invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
@property(copy, nonatomic) id receivedCustomDataHandler; // @synthesize receivedCustomDataHandler=_receivedCustomDataHandler;
- (void)_connectionStateDidChange:(unsigned int)arg1 error:(id)arg2;
- (void)_connectionDidReceiveCustomData:(id)arg1;
- (void)resignActiveOriginWithCompletionHandler:(id)arg1;
- (void)becomeActiveOriginWithCompletionHandler:(id)arg1;
- (void)sendMediaRemoteCommand:(unsigned int)arg1 withOptions:(id)arg2 completionHandler:(id)arg3;
- (void)sendCustomData:(id)arg1;
- (void)reset;
@property(readonly, nonatomic, getter=isInvalidated) _Bool invalidated;
- (void)connectWithOptions:(unsigned long long)arg1 completion:(id)arg2;
- (void)connectWithCompletion:(id)arg1;
@property(readonly, nonatomic, getter=isConnected) _Bool connected;
- (void)dealloc;
- (id)initWithExternalDevice:(void *)arg1;

@end

