//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSIndexSet, NSMutableDictionary, NSMutableIndexSet, NSMutableSet;

@interface MPChangeDetails : NSObject
{
    NSMutableDictionary *_sectionMoves;
    NSMutableIndexSet *_updatedSectionMoveFromIndexes;
    NSMutableDictionary *_itemMoves;
    NSMutableSet *_updatedItemMoveFromIndexPaths;
    _Bool _isFlatCollection;
    NSIndexSet *_insertedSections;
    NSIndexSet *_deletedSections;
    NSIndexSet *_updatedSections;
    NSArray *_insertedItemIndexPaths;
    NSArray *_deletedItemIndexPaths;
    NSArray *_updatedItemIndexPaths;
}

+ (id)changeDetailsWithPreviousCount:(long long)arg1 finalCount:(long long)arg2 isEqualBlock:(id)arg3 isUpdatedBlock:(id)arg4;

@property(copy, nonatomic) NSArray *updatedItemIndexPaths; // @synthesize updatedItemIndexPaths=_updatedItemIndexPaths;
@property(copy, nonatomic) NSArray *deletedItemIndexPaths; // @synthesize deletedItemIndexPaths=_deletedItemIndexPaths;
@property(copy, nonatomic) NSArray *insertedItemIndexPaths; // @synthesize insertedItemIndexPaths=_insertedItemIndexPaths;
@property(copy, nonatomic) NSIndexSet *updatedSections; // @synthesize updatedSections=_updatedSections;
@property(copy, nonatomic) NSIndexSet *deletedSections; // @synthesize deletedSections=_deletedSections;
@property(copy, nonatomic) NSIndexSet *insertedSections; // @synthesize insertedSections=_insertedSections;
- (void)_finalize;
- (void)enumerateMovesWithBlock:(id)arg1;
@property(readonly, copy, nonatomic) NSIndexSet *updatedIndexes;
@property(readonly, copy, nonatomic) NSIndexSet *deletedIndexes;
@property(readonly, copy, nonatomic) NSIndexSet *insertedIndexes;
- (void)enumerateItemMovesWithBlock:(id)arg1;
- (void)removeItemMoveFromIndexPath:(id)arg1;
- (void)appendItemMoveFromIndexPath:(id)arg1 toIndexPath:(id)arg2 updated:(_Bool)arg3;
- (void)enumerateSectionMovesWithBlock:(id)arg1;
- (void)removeSectionMoveFromIndex:(long long)arg1;
- (void)appendSectionMoveFromIndex:(long long)arg1 toIndex:(long long)arg2 updated:(_Bool)arg3;
- (id)debugDescription;
@property(readonly, nonatomic) _Bool hasChanges;
- (id)description;
- (id)initWithBlock:(id)arg1;

@end

