//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/NSCopying-Protocol.h>

@class MPModelObject, MPSectionedCollection;

@interface MPModelLibraryImportChangeRequest : NSObject
{
    _Bool _shouldLibraryAdd;
    MPModelObject *_referralObject;
    MPSectionedCollection *_modelObjects;
}


@property(nonatomic) _Bool shouldLibraryAdd; // @synthesize shouldLibraryAdd=_shouldLibraryAdd;
@property(copy, nonatomic) MPSectionedCollection *modelObjects; // @synthesize modelObjects=_modelObjects;
@property(copy, nonatomic) MPModelObject *referralObject; // @synthesize referralObject=_referralObject;
- (void)performWithResponseHandler:(id)arg1;
- (id)newOperationWithResponseHandler:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

