//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/MPMediaRemoteEntityArtworkGenerator-Protocol.h>

@class MPArtworkResizeUtility, MPMRNowPlayingPlayerPathWrapper, MPNowPlayingContentItem, MPNowPlayingInfoCenterArtworkContext, MSVLRUDictionary, MSVTimer, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;
@protocol MPNowPlayingInfoLyricsDelegate, MPNowPlayingPlaybackQueueDataSource, MPNowPlayingPlaybackQueueDelegate, OS_dispatch_queue;

@interface MPNowPlayingInfoCenter : NSObject
{
    NSDictionary *_nowPlayingInfo;
    NSDictionary *_queuedNowPlayingInfo;
    NSDictionary *_convertedNowPlayingInfo;
    NSDate *_pushDate;
    NSObject *_accessQueue;
    NSObject *_calloutQueue;
    MPNowPlayingInfoCenterArtworkContext *_publishedContext;
    NSMutableDictionary *_mutatedContentItems;
    NSMutableDictionary *_mutatedPlaybackQueueRequests;
    struct _MSVSignedRange _loadedContentItemsRange;
    struct _MSVSignedRange _requestedContentItemsRange;
    NSMutableArray *_contentItemIdentifiers;
    MSVLRUDictionary *_contentItems;
    MPNowPlayingContentItem *_nowPlayingContentItem;
    unsigned long long _playbackState;
    NSObject *_utilityQueue;
    MPArtworkResizeUtility *_artworkResizeUtility;
    MSVTimer *_contentItemInvalidationTimer;
    id _playbackQueueDataSource;
    id _lyricsDelegate;
    struct {
        void *createPlaybackQueue;
        void *createContentItem;
        void *createChildItem;
        void *metadata;
        void *artwork;
        void *info;
        void *languageOptions;
        void *lyrics;
    } _callbacks;
    void *_fallbackActivity;
    unsigned long long _stateHandle;
    MPMRNowPlayingPlayerPathWrapper *_playerPath;
    id _playbackQueueDelegate;
    NSString *_playerID;
    NSString *_representedApplicationBundleIdentifier;
    NSObject *_dataSourceQueue;
}

+ (id)serviceQueue;
+ (id)infoCenterForPlayerID:(id)arg1;
+ (id)defaultCenter;

@property(retain, nonatomic) NSObject *dataSourceQueue; // @synthesize dataSourceQueue=_dataSourceQueue;
@property(copy, nonatomic) NSString *representedApplicationBundleIdentifier; // @synthesize representedApplicationBundleIdentifier=_representedApplicationBundleIdentifier;
@property(readonly, nonatomic) NSString *playerID; // @synthesize playerID=_playerID;
@property(nonatomic) __weak id playbackQueueDelegate; // @synthesize playbackQueueDelegate=_playbackQueueDelegate;
@property(readonly, nonatomic) MPMRNowPlayingPlayerPathWrapper *playerPath; // @synthesize playerPath=_playerPath;
- (void)_onQueue_pushContentItemsUpdate;
- (void)_contentItemChangedNotification:(id)arg1;
- (void)_onQueue_registerPlaybackQueueDataSourceCallbacks:(id)arg1;
- (void)_onQueue_registerLyricsDelegateCallbacks:(id)arg1;
- (void)_onQueue_clearPlaybackQueueDataSourceCallbacks;
- (void)_onDataSourceQueue_getContentItemIDsInRange:(struct _MSVSignedRange)arg1 completion:(id)arg2;
- (id)_onDataSourceQueue_artworkCatalogForContentItem:(id)arg1;
- (void)_invalidatePlaybackQueueImmediatelyWithCompletion:(id)arg1;
- (void)_getTransportablePlaybackSessionRepresentationWithIdentifier:(id)arg1 preferredSessionType:(id)arg2 completion:(id)arg3;
- (void)_getMetadataForContentItem:(id)arg1 completion:(id)arg2;
- (void *)_createPlaybackQueueForRequest:(void *)arg1;
- (id)_contentItemForIdentifier:(id)arg1 alreadyOnDataSourceQueue:(_Bool)arg2;
- (id)_contentItemForIdentifier:(id)arg1;
- (id)_contentItemIDsInRange:(id)arg1 itemsRange:(id)arg2;
- (id)_childContentItemForContentItem:(id)arg1 index:(long long)arg2;
- (void)_becomeActiveWithCompletion:(id)arg1;
- (id)_artworkCatalogForContentItem:(id)arg1;
@property(readonly, nonatomic) _Bool supportsArtworkCatalogLoading;
- (id)artworkCatalogBlockForContentItem:(id)arg1;
@property(retain, nonatomic) MPNowPlayingContentItem *nowPlayingContentItem;
- (void)invalidatePlaybackQueueWithCompletion:(id)arg1;
- (void)invalidatePlaybackQueue;
@property(nonatomic) __weak id lyricsDelegate;
@property(nonatomic) __weak id playbackQueueDataSource;
- (void)resignActiveSystemFallback;
- (void)becomeActiveSystemFallback;
- (void)becomeActive;
@property(nonatomic) unsigned long long playbackState;
- (void)dealloc;
- (id)init;
- (id)initWithPlayerID:(id)arg1;
- (void)_onQueue_pushNowPlayingInfoAndRetry:(_Bool)arg1;
@property(copy, nonatomic) NSDictionary *nowPlayingInfo; // @dynamic nowPlayingInfo;
- (void)_initializeNowPlayingInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

