//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/MPClientRadioController-Protocol.h>

@class BKSProcessAssertion, NSString, NSXPCConnection;
@protocol OS_dispatch_queue;

@interface MPRadioController : NSObject
{
    NSObject *_accessQueue;
    NSXPCConnection *_connection;
    _Bool _hasLaunchedService;
    _Bool _isRadioAvailable;
    BKSProcessAssertion *_remoteProcessAssertion;
    id _remoteProcessAssertionCompletionHandler;
    long long _remoteProcessAssertionCount;
}


- (void)_getConnectionWithCompletionHandler:(id)arg1;
- (void)_setRadioAvailable:(_Bool)arg1;
- (void)_endRemoteProcessAssertion;
- (void)_beginRemoteProcessAssertionWithCompletionHandler:(id)arg1;
- (void)getRecentStationGroupsWithCompletionHandler:(id)arg1;
@property(readonly, nonatomic, getter=isRadioAvailable) _Bool radioAvailable;
- (void)clientRadioControllerRecentStationsDidChange;
- (void)clientRadioControllerRadioAvailabilityDidChange:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

