//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/NSCopying-Protocol.h>
#import <MediaPlayer/NSMutableCopying-Protocol.h>
#import <MediaPlayer/NSSecureCoding-Protocol.h>
#import <MediaPlayer/_MPStateDumpPropertyListTransformable-Protocol.h>

@class NSArray, NSString;

@interface MPSectionedCollection : NSObject
{
    NSArray *_sectionedItems;
    NSArray *_sections;
}

+ (_Bool)supportsSecureCoding;

- (void)_initializeAsEmptySectionedCollection;
- (id)_stateDumpObject;
- (id)changeDetailsToSectionedCollection:(id)arg1 isEqualBlock:(id)arg2 isUpdatedBlock:(id)arg3;
@property(readonly, nonatomic) long long totalItemCount;
@property(readonly, nonatomic) id lastSection;
- (_Bool)hasSameContentAsSectionedCollection:(id)arg1;
- (id)itemsInSectionAtIndex:(long long)arg1;
- (id)indexPathForGlobalIndex:(long long)arg1;
- (long long)globalIndexForIndexPath:(id)arg1;
@property(readonly, nonatomic) id firstSection;
- (void)enumerateItemsUsingBlock:(id)arg1;
- (void)enumerateItemsInSectionAtIndex:(long long)arg1 usingBlock:(id)arg2;
- (void)enumerateSectionsUsingBlock:(id)arg1;
- (id)itemAtIndexPath:(id)arg1;
- (long long)numberOfItemsInSection:(long long)arg1;
- (id)sectionAtIndex:(long long)arg1;
- (long long)numberOfSections;
- (id)allSections;
- (id)allItems;
@property(readonly, nonatomic) id lastItem;
@property(readonly, nonatomic) id firstItem;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSString *debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)indexPathForItemWithIdentifiersIntersectingSet:(id)arg1;
- (id)identifiersForSectionAtIndex:(long long)arg1;
- (id)identifiersForItemAtIndexPath:(id)arg1;
- (void)enumerateItemIdentifiersInSectionAtIndex:(long long)arg1 usingBlock:(id)arg2;
- (void)enumerateSectionIdentifiersUsingBlock:(id)arg1;
- (void)enumerateItemIdentifiersUsingBlock:(id)arg1;

// Remaining properties
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

