//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSOperationQueue;

@interface MPStoreContentReporter : NSObject
{
    NSOperationQueue *_operationQueue;
    NSDictionary *_reportConcernBagDictionary;
}

+ (id)sharedReporter;

- (id)_deletePostURLComponentsFromBag:(id)arg1;
- (id)_deleteCommentURLComponentsFromBag:(id)arg1;
- (id)_reportConcernBagDictionary;
- (id)_dictionariesForType:(long long)arg1;
- (id)baseURLStringForReport;
- (id)reportsForType:(long long)arg1 contentID:(id)arg2 aucType:(id)arg3 commentText:(id)arg4;
- (void)_performWithBag:(id)arg1;
- (void)deletePost:(id)arg1 completion:(id)arg2;
- (void)deleteComment:(id)arg1 activityID:(id)arg2 completion:(id)arg3;
- (void)submitReport:(id)arg1 completion:(id)arg2;
- (id)init;

@end

