//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <MediaPlayer/NSCopying-Protocol.h>

@class NSArray;
@protocol NSCopying;

@interface MPTiledArtworkRequest : NSObject
{
    struct os_unfair_lock_s _cacheLock;
    NSArray *_artworkCatalogsCache;
    long long _artworkCatalogsCacheCount;
    _Bool _allowsSynchronousArtworkCatalogsBlockExecution;
    id _artworkCatalogsBlock;
    unsigned long long _numberOfColumns;
    unsigned long long _numberOfRows;
    double _tileSpacing;
    id _entityIdentifier;
    id _namespaceIdentifier;
    id _revisionIdentifier;
}


@property(copy, nonatomic) id revisionIdentifier; // @synthesize revisionIdentifier=_revisionIdentifier;
@property(copy, nonatomic) id namespaceIdentifier; // @synthesize namespaceIdentifier=_namespaceIdentifier;
@property(copy, nonatomic) id entityIdentifier; // @synthesize entityIdentifier=_entityIdentifier;
@property(nonatomic) double tileSpacing; // @synthesize tileSpacing=_tileSpacing;
@property(nonatomic) unsigned long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(nonatomic) unsigned long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) _Bool allowsSynchronousArtworkCatalogsBlockExecution; // @synthesize allowsSynchronousArtworkCatalogsBlockExecution=_allowsSynchronousArtworkCatalogsBlockExecution;
@property(copy, nonatomic) id artworkCatalogsBlock; // @synthesize artworkCatalogsBlock=_artworkCatalogsBlock;
- (_Bool)hasExistingArtworkCatalogsWithCount:(long long)arg1;
- (id)existingArtworkCatalogsWithCount:(long long)arg1;
- (id)artworkCatalogsWithCount:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

