//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import "CommunicationFilterItem.h"

@class CommunicationsFilterBlockListCache, NSMutableArray, NSObject;

__attribute__((visibility("hidden")))
@interface CommunicationsFilterBlockList : NSObject
{
    NSObject *_connection;
    int _retries;
    NSObject *_queue;
    NSMutableArray *_recentObjectsTested;
    CommunicationsFilterBlockListCache *_cache;
}

+ (CommunicationsFilterBlockList*)sharedInstance;
- (void)_disconnected;
- (BOOL)_disconnect;
- (BOOL)_connect;
- (void)_sendXPCRequest:(id)arg1 completionBlock:(id)arg2;
- (id)_sendSynchronousXPCRequest:(id)arg1;
- (BOOL)isItemInList:(id)arg1;
- (NSArray<CommunicationFilterItem*>*)copyAllItems;
- (void)removeItemForAllServices:(id)arg1;
- (void)addItemForAllServices:(id)arg1;
- (void)dealloc;
- (id)init;

@end

