//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ContactsFoundation/CNTask.h>

@interface _CNBlockTask : CNTask
{
    id _block;
}


- (id)run:(id )arg1;
- (id)initWithName:(id)arg1 block:(id)arg2;
- (id)initWithBlock:(id)arg1;
- (id)initWithName:(id)arg1;

@end

