//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNObserver.h"

@class CNSuspendableSchedulerDecorator, NSString;

@interface _CNBufferedObserver : NSObject
{
    CNSuspendableSchedulerDecorator *_observerScheduler;
    id _observer;
}

+ (id)bufferObserver:(id)arg1 schedulerProvider:(id)arg2;

@property(readonly, nonatomic) CNSuspendableSchedulerDecorator *observerScheduler; // @synthesize observerScheduler=_observerScheduler;
@property(readonly, nonatomic) id observer; // @synthesize observer=_observer;
- (void)observerDidFailWithError:(id)arg1;
- (void)observerDidComplete;
- (void)observerDidReceiveResult:(id)arg1;
- (void)resume;
- (id)initWithObserver:(id)arg1 scheduler:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

