//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNFutureImpl.h"

@class CNFutureResult, CNSuspendableSchedulerDecorator, NSConditionLock, NSString;

@interface _CNBlockFutureImpl : NSObject
{
    NSConditionLock *_stateLock;
    CNFutureResult *_futureResult;
    CNSuspendableSchedulerDecorator *_blockScheduler;
    BOOL _queueSuspended;
    BOOL _workBlockScheduled;
}

+ (id)lazyImplWithSchedulerProvider:(id)arg1 block:(id)arg2;
+ (id)lazyImplWithBlock:(id)arg1;
+ (id)implWithSchedulerProvider:(id)arg1 block:(id)arg2;
+ (id)implWithBlock:(id)arg1;

@property(readonly, nonatomic) CNSuspendableSchedulerDecorator *blockScheduler; // @synthesize blockScheduler=_blockScheduler;
@property(readonly, nonatomic) NSConditionLock *stateLock; // @synthesize stateLock=_stateLock;
@property(nonatomic) BOOL workBlockScheduled; // @synthesize workBlockScheduled=_workBlockScheduled;
- (void)_flushCompletionBlocks;
- (id)futureResult;
- (void)addFailureBlock:(id)arg1;
- (void)addSuccessBlock:(id)arg1;
- (BOOL)finishWithResult:(id)arg1 error:(id)arg2;
- (BOOL)cancel;
- (BOOL)nts_isFinished;
- (BOOL)isCancelled;
- (BOOL)_nts_isFinished;
- (BOOL)isFinished;
- (id)futureResultFromAsynchronousLookupBeforeDate:(id)arg1 error:(id )arg2;
- (id)futureResultFromImmediateLookup;
- (id)resultBeforeDate:(id)arg1 error:(id )arg2;
- (void)addWriterBlock:(id)arg1;
- (void)nts_resumeQueue;
- (BOOL)nts_mayResumeQueue;
- (void)resumeQueue;
- (void)implicitlyResumeQueue;
- (void)updateDescriptionWithBuilder:(id)arg1;
- (void)dealloc;
- (id)initWithSchedulerProvider:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

