//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNCacheBoundingStrategy.h"

@class CNQueue, NSString;

@interface _CNCacheFixedCapacityBoundingStrategy : NSObject
{
    CNQueue *_keys;
    unsigned long long _capacity;
}


@property(readonly, nonatomic) unsigned long long capacity; // @synthesize capacity=_capacity;
@property(readonly, nonatomic) CNQueue *keys; // @synthesize keys=_keys;
- (void)willAccessKey:(id)arg1;
- (BOOL)shouldEvictKey:(id)arg1;
- (void)willUpdateCacheBy:(unsigned long long)arg1 forKey:(id)arg2 keysToEvict:(id )arg3;
@property(readonly, copy) NSString *description;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

