//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ContactsFoundation/CNObservable.h>

@interface _CNFlatMapObservable : CNObservable
{
    CNObservable *_observable;
    id _decoratorGenerator;
    id _schedulerProvider;
}

+ (id)observableWithObservable:(id)arg1 transform:(id)arg2 decoratorGenerator:(id)arg3 schedulerProvider:(id)arg4;
+ (id)flatMapWithObservable:(id)arg1 transform:(id)arg2 schedulerProvider:(id)arg3;
+ (id)concatMapWithObservable:(id)arg1 transform:(id)arg2 schedulerProvider:(id)arg3;

@property(readonly) id schedulerProvider; // @synthesize schedulerProvider=_schedulerProvider;
@property(readonly, copy) id decoratorGenerator; // @synthesize decoratorGenerator=_decoratorGenerator;
@property(readonly) CNObservable *observable; // @synthesize observable=_observable;
- (id)subscribeInnerObservable:(id)arg1 observer:(id)arg2 context:(id)arg3;
- (id)subscribe:(id)arg1;
- (id)initWithObservable:(id)arg1 transform:(id)arg2 decoratorGenerator:(id)arg3 schedulerProvider:(id)arg4;

@end

