//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ContactsFoundation/CNObservable.h>

#import "_CNObservableSkipUntilInputObserverDelegate.h"
#import "_CNObservableSkipUntilSignalObserverDelegate.h"

@class NSString;

@interface _CNObservableSkipUntilOperator : CNObservable <_CNObservableSkipUntilSignalObserverDelegate, _CNObservableSkipUntilInputObserverDelegate>
{
    BOOL _active;
    CNObservable *_input;
    CNObservable *_signal;
    id  _inputToken;
    id  _signalToken;
}


@property(retain) id  signalToken; // @synthesize signalToken=_signalToken;
@property(retain) id  inputToken; // @synthesize inputToken=_inputToken;
@property(getter=isActive) BOOL active; // @synthesize active=_active;
@property(readonly) CNObservable *signal; // @synthesize signal=_signal;
@property(readonly) CNObservable *input; // @synthesize input=_input;
- (void)signalDidGenerateEvent;
- (void)inputDidTerminate;
- (BOOL)shouldMirrorEvents;
- (void)cancel;
- (id)subscribe:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithInput:(id)arg1 signal:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

