//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ContactsFoundation/CNInhibitor.h>

@class NSObject, NSString;

@interface _CNOSTransactionInhibitor : CNInhibitor
{
    NSString *_label;
    NSObject *_transaction;
}


@property(readonly, nonatomic) NSObject *transaction; // @synthesize transaction=_transaction;
@property(readonly, copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void)stop;
- (void)start;
- (id)initWithLabel:(id)arg1;

@end

