//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>



@class NSString;

@interface _CNOffMainThreadScheduler : NSObject
{
    id _alreadyOffMainThreadScheduler;
    id _needToGetOffMainThreadScheduler;
}

+ (id)os_log;

@property(readonly, nonatomic) id needToGetOffMainThreadScheduler; // @synthesize needToGetOffMainThreadScheduler=_needToGetOffMainThreadScheduler;
@property(readonly, nonatomic) id alreadyOffMainThreadScheduler; // @synthesize alreadyOffMainThreadScheduler=_alreadyOffMainThreadScheduler;
@property(readonly) double timestamp;
- (id)afterDelay:(double)arg1 performBlock:(id)arg2 qualityOfService:(unsigned long long)arg3;
- (id)afterDelay:(double)arg1 performBlock:(id)arg2;
- (id)performCancelableBlock:(id)arg1 qualityOfService:(unsigned long long)arg2;
- (id)performCancelableBlock:(id)arg1;
- (void)performBlock:(id)arg1 qualityOfService:(unsigned long long)arg2;
- (void)performBlock:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithBackgroundScheduler:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

