//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "_CNBufferingStrategy.h"

@class NSString;

@interface _CNTemporalBufferingStrategy : NSObject
{
    double _interval;
    id _scheduler;
    id  _sendToken;
}


@property(retain) id  sendToken; // @synthesize sendToken=_sendToken;
- (void)bufferDidSendResults:(id)arg1;
- (void)buffer:(id)arg1 didReceiveResults:(id)arg2 forObserver:(id)arg3;
- (id)initWithTimeInterval:(double)arg1 scheduler:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

