//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSNumber;

@interface CNAuthorizationContext : NSObject
{
    NSNumber *_number_isFirstParty;
    BOOL _hasAuditToken;
    Class _entitlementVerifierClass;

}


@property(readonly) Class entitlementVerifierClass; // @synthesize entitlementVerifierClass=_entitlementVerifierClass;
@property(readonly) BOOL hasAuditToken; // @synthesize hasAuditToken=_hasAuditToken;
 // @synthesize auditToken=_auditToken;
@property(readonly) BOOL isValidatingFirstPartyClient;
- (id)_isFirstParty;
- (id)initWithEntitlementVerifier:(Class)arg1 isFirstParty:(BOOL)arg2;
- (id)initWithAuditToken:(id)arg1;

@end

