//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "CNObservable.h"
#import "CNObserver.h"

@class CNObservableContractEnforcement, CNObservableEvent, NSMutableArray, NSString;

@interface CNBehaviorSubject : NSObject
{
    NSMutableArray *_observers;
    CNObservableEvent *_mostRecentEvent;
    id _schedulerProvider;
    id _resourceLock;
    CNObservableContractEnforcement *_enforcement;
}


@property(readonly, nonatomic) CNObservableContractEnforcement *enforcement; // @synthesize enforcement=_enforcement;
@property(readonly, nonatomic) id resourceLock; // @synthesize resourceLock=_resourceLock;
@property(readonly, nonatomic) id schedulerProvider; // @synthesize schedulerProvider=_schedulerProvider;
@property(retain, nonatomic) CNObservableEvent *mostRecentEvent; // @synthesize mostRecentEvent=_mostRecentEvent;
@property(retain, nonatomic) NSMutableArray *observers; // @synthesize observers=_observers;
- (void)observerDidFailWithError:(id)arg1;
- (void)observerDidComplete;
- (void)observerDidReceiveResult:(id)arg1;
- (void)_removeObserver:(id)arg1;
- (id)_addObserver:(id)arg1;
- (id)subscribe:(id)arg1;
- (void)performWithResourceLock:(id)arg1;
- (id)resultWithResourceLock:(id)arg1;
- (id)initWithSeed:(id)arg1 schedulerProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

