//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import <Foundation/Foundation.h>

@class NSObject, NSString;

@interface CNBinarySemaphoreLock : NSObject
{
    NSObject *_semaphore;
    NSString *_name;
}


@property(copy) NSString *name; // @synthesize name=_name;
- (id)description;
- (void)unlock;
- (void)lock;
- (void)invalidate;
- (void)dealloc;
- (id)init;

@end

