//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface CNBlockCountingSchedulerDecorator : NSObject
{
    id _scheduler;
    unsigned long long _pendingBlockCount;
    unsigned long long _activeBlockCount;
    unsigned long long _completedBlockCount;
}

+ (id)os_log;

@property(readonly, nonatomic) unsigned long long completedBlockCount; // @synthesize completedBlockCount=_completedBlockCount;
@property(readonly, nonatomic) unsigned long long activeBlockCount; // @synthesize activeBlockCount=_activeBlockCount;
@property(readonly, nonatomic) unsigned long long pendingBlockCount; // @synthesize pendingBlockCount=_pendingBlockCount;
@property(readonly, nonatomic) id scheduler; // @synthesize scheduler=_scheduler;
@property(readonly) double timestamp;
- (id)afterDelay:(double)arg1 performBlock:(id)arg2 qualityOfService:(unsigned long long)arg3;
- (id)afterDelay:(double)arg1 performBlock:(id)arg2;
- (id)performCancelableBlock:(id)arg1 qualityOfService:(unsigned long long)arg2;
- (id)performCancelableBlock:(id)arg1;
- (void)performBlock:(id)arg1 qualityOfService:(unsigned long long)arg2;
- (void)performBlock:(id)arg1;
- (void)blockBecameCompleted;
- (void)blockBecameActive;
- (void)blockBecamePending;
@property(readonly, copy) NSString *description;
- (id)initWithScheduler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

