//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface CNCache : NSObject
{
    NSArray *_boundingStrategies;
    id _resourceScheduler;
    NSMutableDictionary *_storage;
    NSMutableArray *_didEvictHandlers;
    NSArray *_evictedKeysAndValues;
}

+ (id)boundingStrategyWithTTL:(double)arg1 timeProvider:(id)arg2;
+ (id)boundingStrategyWithTTL:(double)arg1;
+ (id)boundingStrategyWithCapacity:(unsigned long long)arg1;
+ (id)nonatomicCacheScheduler;
+ (id)atomicCacheScheduler;
+ (id)atomicCache;
+ (id)cache;

@property(copy, nonatomic) NSArray *evictedKeysAndValues; // @synthesize evictedKeysAndValues=_evictedKeysAndValues;
@property(readonly, nonatomic) NSMutableArray *didEvictHandlers; // @synthesize didEvictHandlers=_didEvictHandlers;
@property(readonly, nonatomic) NSMutableDictionary *storage; // @synthesize storage=_storage;
@property(readonly, nonatomic) id resourceScheduler; // @synthesize resourceScheduler=_resourceScheduler;
@property(readonly, copy, nonatomic) NSArray *boundingStrategies; // @synthesize boundingStrategies=_boundingStrategies;
- (void)callDidEvictHandlersIfNecessary;
- (void)resourceLock_evictObjectsForKeys:(id)arg1;
- (void)resourceLock_evictObjectForKey:(id)arg1;
- (void)resourceLock_validateAllKeys;
- (void)resourceLock_validateKey:(id)arg1;
- (void)resourceLock_willAccessKey:(id)arg1;
- (void)resourceLock_willSetObject:(id)arg1 forKey:(id)arg2;
- (void)addDidEvictHandler:(id)arg1;
- (void)removeAllObjects;
@property(readonly, copy) NSArray *allObjects;
@property(readonly, copy) NSArray *allKeys;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)resourceLock_setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1 onCacheMiss:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)resultWithResourceLock:(id)arg1;
- (void)performWithResourceLock:(id)arg1;
- (id)description;
- (id)initWithBoundingStrategies:(id)arg1 resourceScheduler:(id)arg2;
- (id)initWithResourceScheduler:(id)arg1;
- (id)init;

@end

