//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CNEmailAddressScanner : NSObject
{
}

- (void)withEmailAddressesInString:(id)arg1 each:(id)arg2;
- (void)enumerateEmailAddressesInString:(id)arg1 usingBlock:(id)arg2;
- (id)firstEmailAddressInString:(id)arg1;

@end

