//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CNEqualsBuilder : NSObject
{
}

+ (BOOL)isDouble:(double)arg1 equalToOther:(double)arg2 withAccuracy:(double)arg3;
+ (BOOL)isInteger:(long long)arg1 equalToOther:(long long)arg2;
+ (BOOL)isBool:(BOOL)arg1 equalToOther:(BOOL)arg2;
+ (BOOL)isString:(id)arg1 localizedCaseInsensitiveEqualToOther:(id)arg2;
+ (BOOL)isObject:(id)arg1 equalToOther:(id)arg2;
+ (BOOL)evaluateBuilderBlock:(id)arg1 remainingBlocks:(id)arg2;
+ (BOOL)isObject:(id)arg1 memberOfSameClassAndEqualTo:(id)arg2 withBlocks:(id)arg3;
+ (BOOL)isObject:(id)arg1 memberOfClass:(Class)arg2 andEqualToObject:(id)arg3 withBlocks:(id)arg4;
+ (BOOL)isObject:(id)arg1 kindOfClass:(Class)arg2 andEqualToObject:(id)arg3 withBlocks:(id)arg4;
+ (BOOL)isObject:(id)arg1 equalToOther:(id)arg2 withBlocks:(id)arg3;

@end

