//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CNFileUtilities : NSObject
{
    id _services;
}

+ (id)requestSharedLockDirectoryURLWithFileServices:(id)arg1;
+ (id)sharedLockDirectoryURLWithFileServices:(id)arg1;
+ (id)initializeFileLock;
+ (id)fileLock;
+ (id)sharedInstance;
+ (id)os_log;

- (id)proxyLockUrlForFileAtUrl:(id)arg1;
- (id)sharedLockUrlWithName:(id)arg1;
- (id)sharedLockDirectoryUrl;
- (BOOL)isFileAtUrlOnARemoteFileSystem:(id)arg1;
- (id)initWithFileServices:(id)arg1;
- (id)init;

@end

