//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNFuture.h"
#import "CNPromise.h"

@class CNFutureCompletionBlocks, CNFutureResult, CNTask, NSConditionLock, NSString;

@interface CNFutureTask : NSObject
{
    NSConditionLock *_stateLock;
    CNFutureResult *_futureResult;
    CNTask *_task;
    CNFutureCompletionBlocks *_completionBlocks;
}


- (id)recover:(id)arg1;
- (id)flatMap:(id)arg1;
- (void)_flushCompletionBlocks;
- (id)futureResult;
- (void)addFailureBlock:(id)arg1 scheduler:(id)arg2;
- (void)addFailureBlock:(id)arg1;
- (void)addSuccessBlock:(id)arg1 scheduler:(id)arg2;
- (void)addSuccessBlock:(id)arg1;
- (id)errorOnlyCompletionHandlerAdapter;
- (id)boolErrorCompletionHandlerAdapter;
- (id)completionHandlerAdapterWithDefaultValue:(id)arg1;
- (id)completionHandlerAdapter;
- (BOOL)finishWithError:(id)arg1;
- (BOOL)finishWithResult:(id)arg1;
- (BOOL)finishWithResult:(id)arg1 error:(id)arg2;
- (BOOL)run;
- (void)didCancel;
- (BOOL)cancel;
- (BOOL)nts_isFinished;
@property(readonly, getter=isCancelled) BOOL cancelled;
@property(readonly, getter=isFinished) BOOL finished;
- (id)resultWithTimeout:(double)arg1 error:(id )arg2;
- (id)resultBeforeDate:(id)arg1 error:(id )arg2;
- (id)result:(id )arg1;
- (id)initWithTask:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

