//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSMutableArray;

@interface CNFutureCompletionBlocks : NSObject
{
    NSMutableArray *_completionBlocks;
    BOOL _shouldCallImmediately;
}


- (void)flushCompletionBlocksWithFutureResult:(id)arg1;
- (void)addCompletionBlock:(id)arg1 orCallWithFutureResult:(id)arg2;
- (void)addFailureBlock:(id)arg1 orCallWithFutureResult:(id)arg2;
- (void)addSuccessBlock:(id)arg1 orCallWithFutureResult:(id)arg2;
- (void)setShouldCallImmediately:(BOOL)arg1;
- (BOOL)shouldCallImmediately;
- (id)init;

@end

