//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSObject;

@interface CNLaunchServices : NSObject
{
    id _adapter;
    NSObject *_log;
}


@property(retain, nonatomic) NSObject *log; // @synthesize log=_log;
@property(retain, nonatomic) id adapter; // @synthesize adapter=_adapter;
- (void)openSensitiveURLInBackground:(id)arg1 withOptions:(id)arg2 completionHandler:(id)arg3;
- (void)openUserActivityData:(id)arg1 inApplication:(id)arg2 completionHandler:(id)arg3;
- (id)applicationForBundleIdentifier:(id)arg1;
- (id)applicationsForUserActivityType:(id)arg1;
- (id)applicationsAvailableForHandlingURLScheme:(id)arg1;
- (id)initWithAdapter:(id)arg1;
- (id)init;

@end

