//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

#import "CNLaunchServicesAdapter.h"

@class LSApplicationWorkspace;

@interface CNLaunchServicesLocalAdapter : NSObject
{
    LSApplicationWorkspace *_workspace;
}

+ (id)lsApplicationWorkspaceForBundleId:(id)arg1;

@property(retain, nonatomic) LSApplicationWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)openSensitiveURLInBackground:(id)arg1 withOptions:(id)arg2 withReply:(id)arg3;
- (void)openUserActivityData:(id)arg1 inApplication:(id)arg2 withReply:(id)arg3;
- (void)applicationForBundleIdentifier:(id)arg1 withReply:(id)arg2;
- (void)applicationsAvailableForHandlingURLScheme:(id)arg1 withReply:(id)arg2;
- (void)applicationsForUserActivityType:(id)arg1 withReply:(id)arg2;
- (id)initWithApplicationWorkspace:(id)arg1;

@end

