//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNObservable.h"
#import "CNObserver.h"

@class CNObservableContractEnforcement, NSMutableArray, NSString, CNObservable;

@interface CNPublishingSubject : NSObject
{
    CNObservable *_observable;
    id  _upstreamToken;
    NSMutableArray *_observers;
    CNObservableContractEnforcement *_enforcement;
}


@property(readonly, nonatomic) CNObservableContractEnforcement *enforcement; // @synthesize enforcement=_enforcement;
@property(readonly, nonatomic) NSMutableArray *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) id  upstreamToken; // @synthesize upstreamToken=_upstreamToken;
@property(readonly, nonatomic) CNObservable *observable; // @synthesize observable=_observable;
- (void)observerDidFailWithError:(id)arg1;
- (void)observerDidComplete;
- (void)observerDidReceiveResult:(id)arg1;
- (void)_subscribeToObservableIfNecessary;
- (id)_allObservers;
- (void)_removeObserver:(id)arg1;
- (void)_addObserver:(id)arg1;
- (id)subscribe:(id)arg1;
- (id)initWithObservable:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long hash;
@property(readonly) Class superclass;

@end

