//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSArray, NSMutableArray;

@interface CNQueue : NSObject
{
    NSMutableArray *_buffer;
    id _strategy;
}

+ (id)boundedQueueWithCapacity:(unsigned long long)arg1 overflowHandler:(id)arg2;
+ (id)boundedQueueWithCapacity:(unsigned long long)arg1;
+ (id)priorityQueueWithComparator:(id)arg1;

@property(readonly, nonatomic) id strategy; // @synthesize strategy=_strategy;
@property(readonly, nonatomic) NSMutableArray *buffer; // @synthesize buffer=_buffer;
- (id)drain;
- (void)dequeueObject:(id)arg1;
- (id)dequeue;
- (id)peek;
- (void)enqueueObjectsFromArray:(id)arg1;
- (void)enqueue:(id)arg1;
@property(readonly) NSArray *allObjects;
@property(readonly) unsigned long long count;
- (id)initWithStrategy:(id)arg1;
- (id)init;

@end

