//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@protocol CNReaderWriterScheduler
- (void)resume;
- (void)suspend;
- (void)performSynchronousWriterBlock:(void (^)(void))arg1;
- (void)performSynchronousReaderBlock:(void (^)(void))arg1;
- (id )performWriterBlock:(void (^)(id))arg1;
- (id )performReaderBlock:(void (^)(id))arg1;
@end

