//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface CNVirtualSchedulerJob : NSObject
{
    unsigned long long _time;
    id _block;
}

+ (id)jobWithTime:(unsigned long long)arg1 block:(id)arg2;

@property(readonly, copy) id block; // @synthesize block=_block;
@property unsigned long long time; // @synthesize time=_time;
- (id)description;
- (id)initWithTime:(unsigned long long)arg1 block:(id)arg2;

@end

