//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSArray (ContactsFoundation)
+ (id)_cn_arrayWithObject:(id)arg1 count:(unsigned long long)arg2;
- (id)_cn_arrayByRotatingRange:(struct _NSRange)arg1 by:(long long)arg2;
- (BOOL)_cn_isNonEmpty;
- (BOOL)_cn_isIdenticalToArray:(id)arg1;
- (id)_cn_safeSortedArrayUsingComparator:(id)arg1;
- (id)_cn_reversed;
- (void)_cn_zip:(id)arg1 withBlock:(id)arg2;
- (id)_cn_zip:(id)arg1;
- (id)_cn_indexBy:(id)arg1;
- (id)_cn_groupBy:(id)arg1;
- (id)_cn_takeLast:(unsigned long long)arg1;
- (id)_cn_take:(unsigned long long)arg1;
- (id)_cn_sortedArrayUsingAuxiliarySortOrder:(id)arg1 transform:(id)arg2;
- (id)_cn_skipLast:(unsigned long long)arg1;
- (id)_cn_skip:(unsigned long long)arg1;
- (id)_cn_reduce:(id)arg1 initialValue:(id)arg2;
- (id)_cn_reduce:(id)arg1;
- (id)_cn_flatMap:(id)arg1;
- (id)_cn_flatten;
- (id)_cn_distinctObjects;
- (id)_cn_indicesForObjects:(id)arg1;
- (BOOL)_cn_containsObject:(id)arg1;
- (BOOL)_cn_none:(id)arg1;
- (BOOL)_cn_any:(id)arg1;
- (BOOL)_cn_all:(id)arg1;
- (id)_cn_tail;
- (unsigned long long)_cn_indexOfFirstObjectPassingTest:(id)arg1;
- (id)_cn_firstObjectPassingTest:(id)arg1;
- (id)_cn_balancedSlicesWithMaximumCount:(unsigned long long)arg1;
- (id)_cn_slicesWithMaximumCount:(unsigned long long)arg1;
- (id)_cn_partition:(id)arg1;
- (id)_cn_filter:(id)arg1;
- (id)_cn_compactMap:(id)arg1;
- (id)_cn_concurrentMap:(id)arg1;
- (id)_cn_map:(id)arg1;
- (id)_cn_joinWithBlock:(id)arg1;
- (id)_cn_join:(id)arg1;
- (void)_cn_each_reverse:(id)arg1;
- (void)_cn_each:(id)arg1 untilCancelled:(id)arg2;
- (void)_cn_each:(id)arg1 until:(id)arg2;
- (void)_cn_each:(id)arg1;
@end

