//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSNumber (ContactsFoundation)
@property(readonly, nonatomic) double _cn_timeIntervalValue;
- (void)_cn_times:(id)arg1;
@end

