//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface NSSet (ContactsFoundation)
- (id)_cn_indexBy:(id)arg1;
- (id)_cn_firstObjectPassingTest:(id)arg1;
- (id)_cn_filter:(id)arg1;
- (id)_cn_map:(id)arg1;
- (BOOL)_cn_any:(id)arg1;
@end

